### ISSUE TITLE
Unable to have any information after export

### ISSUE THREAD

**Issue by pierrocknroll** [pascalbaljetmedia/laravel-ffmpeg#100]
Hey,

When using :
```
$audio->export()
  ->toDisk('audio')
  ->inFormat(new Mp3())
  ->save($hashName);
```
It's impossible to have any information of the exported file.
Then, it could be great that your File class extends \SplFileInfo to have its very useful functions like getSize, getMimeType, etc

Thanks

**Comment by pascalbaljet** [comment]
It returns the Media object so you can chain multiple exports. Use the `Storage` facade to get file metadata:

```php
use Illuminate\Support\Facades\Storage;

$size = Storage::disk(‘audio’)->size($hashName);
```
