### ISSUE TITLE
Adding custom parameters to the command

### ISSUE THREAD

**Issue by RosiersRobin** [pascalbaljetmedia/laravel-ffmpeg#104]
So I'm trying to execute the follwoing:

```
$media = FFMpeg::fromDisk('shared_host')->open('axis-ACCC8E592904\20180221\15\20180221_155150_E932_ACCC8E592904\20180221_15\20180221_155150_E932_ACCC8E592904.mkv')
                                                ->export()
                                                ->inFormat(new \FFMpeg\Format\Video\X264)
                                                ->save('axis-ACCC8E592904\20180221\15\20180221_155150_E932_ACCC8E592904\20180221_15\test.mp4');
```

which works as it should, but I don't want any quality loss of the converted video... (it needs to be MP4, but size doesn't matter)... How should I get the quality not to get lost here?

I thought adding `-qscale 0` would do the trick, but I have no clue what so ever on how to do this.

**Comment by pascalbaljet** [comment]
Adding custom filters is described in the README: https://github.com/pascalbaljetmedia/laravel-ffmpeg#usage

**Comment by RosiersRobin** [comment]
Yes, I added some, that DOES NOT WORK....
```php
$media = FFMpeg::fromDisk('shared_host')->open("{$path}\\{$recording_id}.mkv")
                                                ->export()
                                                ->inFormat(new \FFMpeg\Format\Video\X264)
                                                ->addFilter(['-qscale', 0])
                                                ->save("{$path}\\{$recording_id}.mp4");
```

Gives the same output as code mentioned in the begin question.... also `->addFilter(['-qscale 0'])` gives the same (big) quality loss on the file. If you see the file size difference it states enough; https://i.imgur.com/VGmNJfG.png

**Comment by pascalbaljet** [comment]
No need to use all caps.
