### ISSUE TITLE
problem generating m3u8

### ISSUE THREAD

**Issue by oixan** [pascalbaljetmedia/laravel-ffmpeg#105]
I have implemented a really base example to test the HLS export function.
this is my code: 

`      $format = new FFMpeg\Format\Video\X264('libmp3lame', 'libx264');

        $lowBitrate = ($format)->setKiloBitrate(250);
        $midBitrate = ($format)->setKiloBitrate(500);
        $highBitrate = ($format)->setKiloBitrate(1000);
      
        FFMpeg::fromDisk('local')
            ->open("video\\QtC9GsAHeU8KgHbqo2ha9ep2nA3iZthQV79mHEDJ.mkv")
            ->exportForHLS()
            ->setSegmentLength(10) // optional
            ->addFormat($lowBitrate, function($media) {
                $media->addFilter(function ($filters) {
                    $filters->resize(new \FFMpeg\Coordinate\Dimension(480, 360));
                });
            })
            ->addFormat($highBitrate, function($media) {
                $media->addFilter(function ($filters) {
                    $filters->resize(new \FFMpeg\Coordinate\Dimension(640, 480));
                });
            })
            ->addFormat($highBitrate, function($media) {
                $media->addFilter(function ($filters) {
                    $filters->resize(new \FFMpeg\Coordinate\Dimension(1280, 720));
                });
            })
            ->save('liveVideo/small_steve2.m3u8'); `

The FFMPEG work fine but the result is not what i expect.

I got 3 file:

small_steve2.m3u8
`#EXTM3U             
#EXT-X-STREAM-INF:BANDWIDTH=1000000            
small_steve2_1000.m3u8        
#EXT-X-STREAM-INF:BANDWIDTH=1000000        
small_steve2_1000.m3u8             
#EXT-X-STREAM-INF:BANDWIDTH=1000000            
small_steve2_1000.m3u8`                

small_steve2_1000.m3u8
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:9
#EXTINF:8.633333,
small_steve2_1000_00000.ts
#EXT-X-ENDLIST`

small_steve2_1000_00000.ts - the file video.

But i expect:

small_steve2.m3u8
`#EXTM3U             
#EXT-X-STREAM-INF:BANDWIDTH=250000            
small_steve2_250.m3u8        
#EXT-X-STREAM-INF:BANDWIDTH=500000        
small_steve2_500.m3u8             
#EXT-X-STREAM-INF:BANDWIDTH=1000000            
small_steve2_1000.m3u8`       

small_steve2_250.m3u8
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:9
#EXTINF:8.633333,
small_steve2_250_00000.ts
#EXT-X-ENDLIST`         

small_steve2_500.m3u8
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:9
#EXTINF:8.633333,
small_steve2_500_00000.ts
#EXT-X-ENDLIST`         

small_steve2_1000.m3u8
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:9
#EXTINF:8.633333,
small_steve2_1000_00000.ts
#EXT-X-ENDLIST`

small_steve2_250_00000.ts - the file video.

small_steve2_500_00000.ts - the file video.

small_steve2_1000_00000.ts - the file video.

What i m mising. 

i m using laravel 5.6 and ffmpet 4.0.2.

To replicate the problem just copy and execute the code on new laravel project and see the result.

**Comment by pascalbaljet** [comment]
These formats are all the same object, you need to create three new instances, see also: http://php.net/manual/en/language.oop5.references.php (read this, it's quite important)

```php
$lowBitrate = ($format)->setKiloBitrate(250);
$midBitrate = ($format)->setKiloBitrate(500);
$highBitrate = ($format)->setKiloBitrate(1000);
```

`$lowBitrate`, `$midBitrate` and `$highBitrate` are all the same. Do it like this:

```php
use FFMpeg\Format\Video\X264;

$lowBitrate = (new X264)->setKiloBitrate(250);
$midBitrate = (new X264)->setKiloBitrate(500);
$highBitrate = (new X264)->setKiloBitrate(1000);
```

**Comment by oixan** [comment]
thanks, now work.
