### ISSUE TITLE
Can't install with Laravel 5.7 

### ISSUE THREAD

**Issue by codiiv** [pascalbaljetmedia/laravel-ffmpeg#107]
Amazing job you've done here. I have a application it works well with Laravel 5.6 but when I tried to upgrade to Laravel 5.7 , It gives an installation error : 

```
- Installation request for laravel/framework 5.7 -> satisfiable by laravel/framework[v5.7.0].
- Installation request for pbmedia/laravel-ffmpeg ^2.1 -> satisfiable by pbmedia/laravel-ffmp
eg[2.1.0, 2.1.1]
```
```
- Conclusion: don't install laravel/framework v5.7.1
- pbmedia/laravel-ffmpeg 2.1.1 requires illuminate/log 5.6.* -> satisfiable by laravel/framew
ork[v5.6.38], illuminate/log[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15
, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.2
6, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.
36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
```

Can you please look into it

**Comment by pascalbaljet** [comment]
I started working on it last week, will tag a new version later today:
https://github.com/pascalbaljetmedia/laravel-ffmpeg/tree/laravel-5.7

**Comment by pascalbaljet** [comment]
v3.0.0 has support for Laravel 5.7 ✌️

**Comment by codiiv** [comment]
On a new installation (Lvl 5.7 ) it worked. UPgrade from 5.6 to 5.7 failed, but not a biggy

**Comment by codiiv** [comment]
I think it conflicted with the other packages I have in the app. Laravel gave me incompatibility message. I remove ffmpeg , run composer update and tried to install again, with no avail. So, I tested with it being the only package and it worked like a charm and added the other ones after, no problem! 

I guess it's a diva package. What dd u create man? :)
