### ISSUE TITLE
Progress Tracking

### ISSUE THREAD

**Issue by Insax** [pascalbaljetmedia/laravel-ffmpeg#11]
As far as I saw it's not possible to track the progress of the file to convert, is this feature planned to be implemented or do I have to find another solution?

**Comment by pascalbaljet** [comment]
It is [supported](https://github.com/PHP-FFMpeg/PHP-FFMpeg#formats) by the underlying driver, just attach a callback method on the format.

```php
$format = new FFMpeg\Format\Video\X264();
$format->on('progress', function ($video, $format, $percentage) {
    echo "$percentage % transcoded";
});
```
