### ISSUE TITLE
Unable to load ffmpeg

### ISSUE THREAD

**Issue by TechTailor** [pascalbaljetmedia/laravel-ffmpeg#110]
I am unable to load ffprobe in my laravel application using the Facade.

I have the config file set properly (using XAMPP on windows for Laravel 5.7 with v3.0.0) and I am even getting response when using - 
```
Route::get('/f', function() {
	$ffmpeg = \FFMpeg\FFMpeg::create([
    'ffmpeg.binaries'  => 'C:/FFmpeg/bin/ffmpeg.exe',
    'ffprobe.binaries' => 'C:/FFmpeg/bin/ffprobe.exe' 
]); dd($ffmpeg);
});
```
However when I am using the Facade FFMpeg i am getting "Unable to load ffprobe" error. 

Would appreciate if you can guide me through a resolve or a work around for the same.

Thanks

**Comment by TechTailor** [comment]
Issue Resolved - have to set the path in windows environment variables for PC.

**Comment by vsfarooqkhan** [comment]
Path also set to the correct path which ffprobe resides. still getting the error
