### ISSUE TITLE
Unable to save concatenated video

### ISSUE THREAD

**Issue by FrancescoMussi** [pascalbaljetmedia/laravel-ffmpeg#112]
I have a similar problem as in https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/42

I have tried to concat two videos:

```
$disk = FFMpeg::fromDisk('public');
$video1 = $disk->open('videos/test1.mp4');
$video2 = $disk->open('videos/test2.mp4');
$output = $disk->open('videos/output.mp4');

$video1->concat([
    $video1->getPathfile(),
    $video2->getPathfile(),
])->saveFromSameCodecs($output->getPathfile(), true);
```

The paths are correct.
No matter what I tried, I am always getting the error: `Unable to save concatenated video`

If I go inside the library and I dump the command: `dd($this->driver->command($commands));` I get this more specific error:

`ffmpeg failed to execute command '/usr/local/bin/ffmpeg' '-f' 'concat' '-safe' '0' '-i' '/private/var/folders/dw/919v2nds7s78pz_qhp7z9rcm0000gn/T/ffmpeg-concat23eyYp' '-c' 'copy' '/Users/francescomussi/Desktop/Apps/cameraProject/back-end/camera-laravel/storage/app/public/videos/output.mp4'`

I noticed that this path exists: `/private/var/folders/dw/919v2nds7s78pz_qhp7z9rcm0000gn/T/` but inside there is no folder `ffmpeg-concat23eyYp`. 
I don't know if that's how it should be. I just noticed it. I see that the name of this temporary folder changes at each command.

If I dump the commands I get the following:

![screen shot 2018-10-01 at 16 59 53](https://user-images.githubusercontent.com/5312907/46293207-75195f80-c59b-11e8-98b0-4cf52bea543f.png)

Everything looks fine until that point. Then it failed to generate the commands.

Do you know why that is happening?

Side question: the file output.mp4 has to already exist, so that it can be overwritten, correct?

**Comment by juanconti** [comment]
Hi, there!
I had a similar problem to yours and a I've found a solution.

The problem with the first example that you gave, is that you are passing an invalid file path (a file that does not exist.). I was doing the exact same thing, but every time that you select a video through the facade, it checks it passing the file path to the ffprobe binary. Given that the video file does not exist it fails the test.

The code that i've tried and has worked is this one:`
$disk = FFMpeg::fromDisk('public');
$video1 = $disk->open('videos/test1.mp4');
$video2 = $disk->open('videos/test2.mp4');

$filepath = "videos/output.mp4";
$output = Storage::disk('public')->getDriver()->getAdapter()->getPathPrefix() . $filepath;

$video1->concat([
    $video1->getPathfile(),
    $video2->getPathfile(),
])->saveFromSameCodecs($output, true);`

You have to give a valid file path whitout using FFMpeg::fromDisk('public')->open() method as the output.

**Comment by FrancescoMussi** [comment]
Thanks @juanconti.
I managed to resolve. In my case the issue was that the output file was already existing, while it shouldn't. 

The error reporting is not detailed, so it took me a while to figure it out.
But the creator of PHP-FFMpeg said they are working on improving the error reporting:

https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/580
