### ISSUE TITLE
There is no sound after using laravel-ffmpeg transcoding m3u8.

### ISSUE THREAD

**Issue by augustdai** [pascalbaljetmedia/laravel-ffmpeg#114]
info:
"laravel/framework": "5.6.*",
"pbmedia/laravel-ffmpeg":"^2.1",

ffmpeg version 4.0.1 Copyright (c) 2000-2018 the FFmpeg developers
built with Apple LLVM version 9.1.0 (clang-902.0.39.2)

When converted to a file, it can only play the picture without sound playing.

###Searching the document can not solve this problem, and seek the author's answer. Thank.###

#Running program
$path = ""; //Resource customization
$save_as = ""; //Resource customization
$lowBitrate = (new X264)->setKiloBitrate(250);
        $midBitrate = (new X264)->setKiloBitrate(500);
        $highBitrate = (new X264)->setKiloBitrate(1000);
        FFMpeg::fromDisk('videos')
        ->open($path)
        ->exportForHLS()
        ->setSegmentLength(3) // optional
        ->addFormat($lowBitrate)
        ->addFormat($midBitrate)
        ->addFormat($highBitrate)
        ->save($save_as);

**Comment by fititnt** [comment]
Hey @augustdai, I believe this could be a problem with your FFMpeg installation or even with the input files.

From my short experience, most issues where or with the binaries of ffmpeg and ffprobe, or things related to php-ffmpeg.

The exportForHLS in special is something from laravel-ffmpeg, but at least this issue with sound I did not had trouble.

**Comment by augustdai** [comment]
Thank you for your reply, the question has been found, as you said, caused by the voice conversion settings. To share the following questions, I post code examples.
##===============
$video  = $ffmpeg->open($path);
        $format = new \FFMpeg\Format\Video\X264('aac', 'libx264');
        $format->on('progress', function ($video, $format, $percentage) {
            echo $percentage . '% ';
            if ($percentage >= 99) {
                var_dump("ok");
            }
        });

**Comment by reniar1** [comment]
@augustdai What was the solution to this question?
