### ISSUE TITLE
How to convert WAV to HLS with this library

### ISSUE THREAD

**Issue by pedrofurtado** [pascalbaljetmedia/laravel-ffmpeg#115]
@pascalbaljet That's a great package, but I could not find a example code about conversion of audios in HLS, but just videos.

How do I convert a audio (mp3 or wav, for example) in HLS with this library? :+1: 

Thanks!

**Comment by pascalbaljet** [comment]
Have you tried something like this?

```
$lowBitrate = (new \FFMpeg\Format\Audio\Aac)->setKiloBitrate(64);
$midBitrate = (new \FFMpeg\Format\Audio\Aac)->setKiloBitrate(128);
$highBitrate = (new \FFMpeg\Format\Audio\Aac)->setKiloBitrate(265);

FFMpeg::fromDisk('songs')
    ->open('steve_howe.mp3')
    ->exportForHLS()
    ->setSegmentLength(10) // optional
    ->addFormat($lowBitrate)
    ->addFormat($midBitrate)
    ->addFormat($highBitrate)
    ->save('adaptive_steve.m3u8');
```

**Comment by pascalbaljet** [comment]
Any updates on this issue?

**Comment by Muntader** [comment]
@pascalbaljet 
It's not working 
`message: "Argument 1 passed to Pbmedia\LaravelFFMpeg\HLSPlaylistExporter::addFormat() must be an instance of FFMpeg\Format\VideoInterface, instance of FFMpeg\Format\Audio\Aac given
`

**Comment by pedrofurtado** [comment]
@pascalbaljet Can you open again the issue? Based on feedback of @Muntader , there is a potential bug 👍
