### ISSUE TITLE
libmp3lame not returning sound when converted to mp4

### ISSUE THREAD

**Issue by Jaspur** [pascalbaljetmedia/laravel-ffmpeg#117]
Hi @pascalbaljet ,
I'm getting this error on Ubuntu: ```Unknown encoder 'libfdk_aac'```, because Ubuntu doesn't work with that codec for audio (found on Google).

So I tried 'libmp3lame' as codec, but that results in a video without audio:
```
FFMpeg::fromDisk('local')
            ->open('videos/0.qt')
            ->export()
            ->toDisk('local')
            ->inFormat(new \FFMpeg\Format\Video\X264('libmp3lame'))
            ->save('videos/0.mp4');
```

**Comment by pascalbaljet** [comment]
Many issues have been opened concerning ffmpeg’s codec support, try building ffmpeg yourself with AAC support.
