### ISSUE TITLE
Increase video quality and reduce weight.

### ISSUE THREAD

**Issue by adriannx** [pascalbaljetmedia/laravel-ffmpeg#119]
Hello,

When coding the videos they manage to have a big weight and the video quality is bad.

I would like to know where the file is located to configure the presets, in relation to this information:
https://trac.ffmpeg.org/wiki/Encode/H.264#a2.Chooseapresetandtune

With this option I will be able to reduce the weight of the videos and increase the quality.

Is it possible to do this?

Best Regards!

**Comment by adriannx** [comment]
@pascalbaljet  
Hello,
Before publishing this topic, I read the documentation and I have not found information related to the increase in quality and weight reduction.

I'll be more precise, because I think you've misunderstood me.

Increasing the Bitrate for better video quality equals increasing the weight of the video.
With CRF the same thing does not happen, this option improves the quality and reduces the weight of the file.

Obviously, having this option in operation requires more consumption of server resources.

**Comment by MarcVertigo** [comment]
When using PHP-FFMpeg I don't use quality. But when converting a video with laravel-ffmpeg I lose a lot of video quality, and I mean a lot.
I tried:
`$format->setAdditionalParameters( [ '-crf', '29' ] );`
With no luck.

**Comment by pokono** [comment]
I'm in the same boat, any news on this?
