### ISSUE TITLE
Video Watermarks

### ISSUE THREAD

**Issue by daniyal92** [pascalbaljetmedia/laravel-ffmpeg#12]
How to add watermarks to videos?

**Comment by pascalbaljet** [comment]
Use the watermark filter class:
https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/master/src/FFMpeg/Filters/Video/WatermarkFilter.php

Please read the documentation, it has a section about filters.

**Comment by daniyal92** [comment]
My code:
`
            $video_file = FFMpeg::fromDisk('public')
            ->open('files/original/'.Auth::user()->id.'/'.$file_name.'.'.$file_extension);

            /* Add watermarks to the video */
            $watermarkFilter = new \FFMpeg\Filters\Video\WatermarkFilter(public_path('assets\img\watermark.png'));

            $video_file->addFilter($watermarkFilter)
            ->export()
            ->toDisk('public')
            ->inFormat(new \FFMpeg\Format\Video\X264('libmp3lame'))
            ->save('files/copy/'.Auth::user()->id.'/'.$file_name.'.'.$file_extension);
`
It gives error "Encoding Failed - ffmpeg failed to execute command"

The same command on the command line results in an error 

"[Parsed_movie_0 @ 04e5bea0] Failed to avformat_open_input 'D'
[AVFilterGraph @ 04e75c60] Error initializing filter 'movie' with args 'D:wampwwwsell-a-videopublicassetsimgwatermark.png'
Error reinitializing filters!
Failed to inject frame into filter network: No such file or directory
Error while processing the decoded data for stream #0:0
[libmp3lame @ 04e5d6a0] 3 frames left in the queue on closing
Conversion failed!"

However when i try a simple command on the command line it works:
`
ffmpeg -i birds.mp4 -i watermark.png -filter_complex "overlay=10:10" birds1.mp4

`
Please help.
