### ISSUE TITLE
Processing time is too long for  clip video

### ISSUE THREAD

**Issue by cheng91jing** [pascalbaljetmedia/laravel-ffmpeg#120]
```php
$this->media
    ->addFilter($clipFilter)
    ->export()
    ->inFormat(new X264($this->audio_code))
    ->save($clip_path);
```
this package generated command：
`/home/vagrant/bin/ffmpeg -y -i test.mp4 -ss 00:48:15.00 -t 00:00:10.00 ......`
It is too slow.
I think the command should look like:
`/home/vagrant/bin/ffmpeg -y -ss 00:48:15.00 -i test.mp4 -t 00:00:10.00 ......`
the parameter <code>-ss 00:48:15.00</code> should be in front of <code>-i test.mp4</code>.
because this is much faster

**Comment by pascalbaljet** [comment]
What does `$clipFilter` look like?

**Comment by pascalbaljet** [comment]
Any updates on this issue?

**Comment by KattieM** [comment]
Hi, I have the same problem:

`$ffprobe = FFProbe::create();
$url = storage_path('app/public/0d5b17aabcae25d9b4ab09de888bc158.mp4');
$video_probe = $ffprobe->streams($url)->videos()->first();

$format = new X264();
$format->setAudioCodec("libfdk_aac");
$format->setVideoCodec('libx264');
$bitrate = $video_probe->get('bit_rate');
$format->setKiloBitrate(round(($bitrate / 1000) + 1, 0));

$start_tc = TimeCode::fromString("00:00:00.00");
$duration_tc = TimeCode::fromString("00:00:20.10");
$clipFilter = new ClipFilter($start_tc, $duration_tc);
$name = md5(time()) . ".mp4";
FFMpeg::fromDisk('public')
->open("my_file_name.mp4")
->export()
->addFilter($clipFilter)
->inFormat($format)
->toDisk('public')
->save("export_here.mp4");
`
What can I do here to make it faster? Currently it takes ~15 seconds to cut video to 20 seconds
);`

**Comment by francoism90** [comment]
I know this is an old issue, hopefully it's useful to anybody:

```php
$segments->each(function (float $seconds, int $key) use ($ffmpeg, $media, &$items) {
            $items[] = $path = "{$media->uuid}_segment_{$key}.mp4";

            $ffmpeg
                ->export()
                ->inFormat((new X264)
                    ->setInitialParameters(['-ss', TimeCode::fromSeconds($seconds), '-t', TimeCode::fromSeconds(2)])
                    ->setKiloBitrate(1500)
                    ->setPasses(1)
                )
                ->toDisk('cache')
                ->save($path);

        });
```

As you can see, you can the `-ss` and `-t` with `setInitialParameters`. This indeed makes it complete in 5 seconds, instead of 2 mins. :)
