### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by laravelcoder** [pascalbaljetmedia/laravel-ffmpeg#121]
I have the your package installed and working great. i have created jobs to process each step of the conversions but i am at a loss on how to add this to the command.

> -vf fps=1 ./snapshot-%4d.png

I need to generate images every second but i dont see anything like that in your wrapper. can you please tell me how i can add it. 

my conversion to mp4 is here 
```

public function handle()
    {
        $lowBitrateFormat = (new X264('aac'))->setKiloBitrate(500);
        $name = $mediaItems[0]->name;
        $file = $mediaItems[0]->file_name;
        $clipid = $mediaItems[0]->id;
        $slug = $title = str_slug($name, "_");

        FFMpeg::fromDisk('videos')->open($clipid . '/'. $file)
            ->addFilter(function ($filters) {
                $filters->resize(new Dimension(960, 540));
            })->export()
            ->toDisk('downloadable_videos')
            ->inFormat($lowBitrateFormat)
            ->save($slug . '.mp4');
 
        Log::info("Job: converted at " .  Carbon::now() . " FINISHED ");
    }
```

**Comment by laravelcoder** [comment]
11 days still no reply.

**Comment by pascalbaljet** [comment]
I've been quite busy the last few weeks and therefore unable to comment on issues. Please mind that this package is free and I have no obligation to anyone to provide any support. I really don't like your attitude so I'm closing this issue and wish you all the best.

**Comment by laravelcoder** [comment]
wow you are really not a good help
