### ISSUE TITLE
Everything i try to get image generation to happen will not work. 

### ISSUE THREAD

**Issue by laravelcoder** [pascalbaljetmedia/laravel-ffmpeg#122]
***Let me start by saying thanks for getting back to me as i am also busy so appreciate your response, sorry for being short with you but i was wondering if you are watching the issues or not. Sorry but it was not meant to offend. I like your package and just need some assistance in making the image generation happen.***

I have the your package installed and working great. i have created jobs to process each step of the conversions but i am at a loss on how to add this to the command.

> -vf fps=1 ./snapshot-%4d.png

I need to generate images every second but i dont see anything like that in your wrapper. can you please tell me how i can add it. 

my conversion to mp4 is here 
```

public function handle()
    {
        $lowBitrateFormat = (new X264('aac'))->setKiloBitrate(500);
        $name = $mediaItems[0]->name;
        $file = $mediaItems[0]->file_name;
        $clipid = $mediaItems[0]->id;
        $slug = $title = str_slug($name, "_");

        FFMpeg::fromDisk('videos')->open($clipid . '/'. $file)
            ->addFilter(function ($filters) {
                $filters->resize(new Dimension(960, 540));
            })->export()
            ->toDisk('downloadable_videos')
            ->inFormat($lowBitrateFormat)
            ->save($slug . '.mp4');
 
        Log::info("Job: converted at " .  Carbon::now() . " FINISHED ");
    }
```
I got this to almost work but its ignoring my naming convetion and falling back on the default.  
any help would be greatly appreciated. 
```
        \FFMpeg::fromDisk('videos')
                    ->open($clipid . '/'. $file)
                   // ->exportForHLS()
                    ->addFilter(function ($filters) {
                        $filters->resize(new Dimension(432, 320));
                   $filters->extractMultipleFrames(ExtractMultipleFramesFilter::FRAMERATE_EVERY_SEC, public_path('uploads/yo'), '/', 100, 2, array('-vf', 'fps=1/1', '/rename-%03d.jpg'));
                    })
                    ->export()
                    ->toDisk('downloadable_videos')
                    ->inFormat($midBitrate)
                    ->save($slug ."/". $slug . '.mp4');
```

One last thing i cannot get the hls filter to function it keeps error out. Do you have an example of how to implement this

**Comment by pascalbaljet** [comment]
I think the problem is that the `extractMultipleFrames` method only takes [two parameters](https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/master/src/FFMpeg/Filters/Video/VideoFilters.php#L68). The output name of the frames are [fixed](https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/master/src/FFMpeg/Filters/Video/ExtractMultipleFramesFilter.php#L138). 

You could also try to add your own filter by using the `addFilter()` method (see documentation).
