### ISSUE TITLE
Unable to load FFProbe (Linux Ubuntu)

### ISSUE THREAD

**Issue by rabichawila** [pascalbaljetmedia/laravel-ffmpeg#126]
**Before i say anything, i should mention how sorry i am for reopening this Issue**
And thank you for your exceptional Package.

Now, i have an issue when using `FFMPEG` in my `laravel 5.7` app.

`FFMpeg \ Exception \ ExecutableNotFoundException` **Unable to load FFProbe**

**Here is the path to my** `FFMPEG` **and** `FFProbe`

```
root@CY-TOOL:~# which ffmpeg
  /usr/bin/ffmpeg
root@CY-TOOL:~# which ffprobe 
 /usr/bin/ffprobe
root@CY-TOOL:~# php -v
PHP 7.2.15-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  8 2019 15:37:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.15-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
 ```

**`App\Config\laravel-ffmpeg.php`**

 just like it is said in [laravel-ffmpeg/config/laravel-ffmpeg-ubuntu.php](https://github.com/pascalbaljetmedia/laravel-ffmpeg/blob/master/config/laravel-ffmpeg-ubuntu.php)

```
 <?php

return [
    'default_disk' => 'local',

    'ffmpeg' => [
        'binaries' => env('FFMPEG_BINARIES', '/usr/bin/ffmpeg'),
        'threads' => 12,
    ],

    'ffprobe' => [
        'binaries' => env('FFPROBE_BINARIES', '/usr/bin/ffprobe'),
    ],

    'timeout' => 3600,
];

?>
```
 

**composer.json**
```

    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "^1.0",
        "pbmedia/laravel-ffmpeg": "^3.0",
        "php-ffmpeg/extras": "^0.3.1"
    }

```

**Please try to answer in such away that we wont have to ask you any  another question anymore(concerning this), because i know it might annoy too when we keep on repeating the same questions again and again**

I am not that advance in laravel so don't use deep terms.

Thanks in advance...

**Comment by pascalbaljet** [comment]
Did you set the `FFMPEG_BINARIES` and `FFPROBE_BINARIES` variables in the `.env` file?

Maybe there is a permissions problem with the ffmpeg binaries? Can the PHP user execute these binaries?

**Comment by rabichawila** [comment]
```
chawila@CY-TOOL:/usr/bin$ ll
-rwxr-xr-x  1 root www-data   235816 Aug 23  2018 ffmpeg*
-rwxr-xr-x  1 root www-data   129336 Aug 23  2018 ffplay*
-rwxr-xr-x  1 root www-data   145400 Aug 23  2018 ffprobe*
-rwxr-xr-x  1 root www-data   138664 Aug 23  2018 ffserver*
```



**.env**

```
FFMPEG_BINARIES=/usr/bin/ffmpeg
FFPROBE_BINARIES=/usr/bin/ffprobe
```

**Comment by rabichawila** [comment]
@pascalbaljet , @laravelish , @joecampo , @plokko 
Guys i know you're offering this package for free and u're not getting paid. i highly appreciate that.

but if u don't have any answer to my problem, please tell me because i'm refreshing the page every 5 minutes hoping to find your comment..  (it's very funny)

Just ask me anything you want, i can give u my GitHub repo if necessary..

Thank you..

**Comment by joecampo** [comment]
The configuration looks okay to me. 

- Are you sure the binaries are installed on the server that you're running your app from? Not running it from homestead/docker etc.?
- Have you tried hardcoding the 'binaries' key to the path instead of using .env? Possible that your .env is cached with the wrong paths? ```php artisan config:clear```

**Comment by rabichawila** [comment]
@joecampo 
Thanks mate, finally it worked...

**Comment by vsfarooqkhan** [comment]
Could you please help me  , how it worked? 
I'm also having the same issue

**Comment by joecampo** [comment]
Hi @vsfarooqkhan. You're not providing much information to be of much help. Did you follow the above thread to try and resolve your issue? The issue isn't with this library, but rather your configuration or environment.

**Comment by duthaho** [comment]
@rabichawila @joecampo Can you please detail what do you tried to worked? I had same issue here. I followed and checked every steps in this thread, I didn't see anything wrong on my project and config. Except:

**Comment by hzburki** [comment]
I am trying to use this package on an Amazon Linux instance hosted on AWS Elastic beanstalk. 

1. I have implemented my solution following the Stackoverflow links [here](https://stackoverflow.com/questions/23340771/install-ffmpeg-on-elastic-beanstalk-using-ebextensions-config). This seems to be the solution that has worked for everyone. 
2. I have also tried hard coding the binary paths as mentioned by @joecampo. My env variables are;
.env file
``` 
FFMPEG_BINARIES=/usr/bin/ffmpeg
FFPROBE_BINARIES=/usr/bin/ffprobe
```
3. After ssh-ing into the instance and running the `cd /usr/bin && ll` command. I can see the ffmpeg  package as;
```
lrwxrwxrwx   1 root root         44 Feb 22 06:20 ffmpeg -> /opt/ffmpeg/ffmpeg-3.4.2-64bit-static/ffmpeg
lrwxrwxrwx   1 root root         45 Feb 22 06:20 ffprobe -> /opt/ffmpeg/ffmpeg-3.4.2-64bit-static/ffprobe
``` 

**Note:**
I've noticed the last command returns a different response for me compared to the ones mentioned above. The Stackoverflow link (share above) created symlinks. So I have also tried to add `/opt/ffmpeg/ffmpeg-3.4.2-64bit-static/ffmpeg` in the env path for binaries as well as hard coding it. 

I am creating a thumbnail for every video uploaded to my app and storing the thumbnail to AWS S3. Surprisingly, my code does not crash and there are no errors but the thumbnail does not get stored on AWS S3.

**Comment by joecampo** [comment]
@hzburki Looks like your configuration is fine to me. As a sanity check have you tried to generate the thumbnails to a local disk (to rule out problems with storing it on S3)?

**Comment by hzburki** [comment]
@joecampo yes ... its works on local. I have windows installed though. Passing the executable paths in the env works with the same code.

**Comment by joecampo** [comment]
@hzburki Sounds like the problem may perhaps be the code storing on S3. I'd try storing it locally on your linux box to see.

**Comment by hzburki** [comment]
The issue was probably that the `.env` was cached by the beanstalk instance. I removed the `.env` all together add hardcoded the values again and it worked.

**Comment by legionlad** [comment]
Here, how i solved it.

For me it was rather un-related. 

I was using SpatieMedia with ffmpeg to clip a video, store it in a temp folder then save .webm in the same directory created by spatiemedia.

The Ffprobe was loading right, it was the hard-coded paths in spatie-media which were wrong.

Fix
vendor\spatie\laravel-medialibrary\config\media-library.php 
 Changed those line to this, on my server Ubuntu 20
   
---------- 

    'ffmpeg_path' => '/usr/bin/ffmpeg',
        'ffprobe_path' =>  '/usr/bin/ffprobe',

----------


vendor\spatie\laravel-medialibrary\src\Conversions\ImageGenerators\Video.php
 Same change in convert() function

----------
 

      $ffmpeg = FFMpeg::create([
                'ffmpeg.binaries' => '/usr/bin/ffmpeg',
                'ffprobe.binaries' => '/usr/bin/ffprobe',
        ]);
----------
