### ISSUE TITLE
Error: Failed to execute command - Encoding Failed

### ISSUE THREAD

**Issue by daniyal92** [pascalbaljetmedia/laravel-ffmpeg#13]
I keep getting this error, even when i try to do some simple video conversion. FFMpeg is working fine, i tested some commands through the command line and it worked fine but i get this error when using this package. Video thumbnails works fine but other video manipulation results in this error.

My code is:
`            

            $video_file = FFMpeg::fromDisk('public')
            ->open('files/original/'.Auth::user()->id.'/'.$file_name.'.'.$file_extension);

            $start = \FFMpeg\Coordinate\TimeCode::fromSeconds(2);
            $clipFilter = new \FFMpeg\Filters\Video\ClipFilter($start);

            $video_file->addFilter(function ($filters) {
                $filters->resize(new \FFMpeg\Coordinate\Dimension(640, 480));
            })
            ->export()
            ->toDisk('public')
            ->inFormat(new \FFMpeg\Format\Video\X264())
            ->save('short_steve.mp4');

`

This is the error i recieve:

ExecutionFailureException in ProcessRunner.php line 100:
ffmpeg failed to execute command "D:/wamp/bin/ffmpeg/bin/ffmpeg.exe" "-y" "-i" "D:\wamp\www\sell-a-video\storage\app/public\files/original/3/3-9lg7hK.mp4" "-ss" "00:00:02.00" "-threads" "12" "-vcodec" "libx264" "-acodec" "libfaac" "-b:v" "1000k" "-refs" "6" "-coder" "1" "-sc_threshold" "40" "-flags" "+loop" "-me_range" "16" "-subq" "7" "-i_qfactor" "0.71" "-qcomp" "0.6" "-qdiff" "4" "-trellis" "1" "-b:a" "128k" "-pass" "1" "-passlogfile" "C:\Windows\TEMP\ffmpeg-passes59082e90450edzn2gy/pass-59082e90454d5" "D:\wamp\www\sell-a-video\storage\app/public\short_steve.mp4"

**Comment by pascalbaljet** [comment]
What is the result of executing this in the command prompt?

```
"D:/wamp/bin/ffmpeg/bin/ffmpeg.exe" "-y" "-i" "D:\wamp\www\sell-a-video\storage\app/public\files/original/3/3-9lg7hK.mp4" "-ss" "00:00:02.00" "-threads" "12" "-vcodec" "libx264" "-acodec" "libfaac" "-b:v" "1000k" "-refs" "6" "-coder" "1" "-sc_threshold" "40" "-flags" "+loop" "-me_range" "16" "-subq" "7" "-i_qfactor" "0.71" "-qcomp" "0.6" "-qdiff" "4" "-trellis" "1" "-b:a" "128k" "-pass" "1" "-passlogfile" "C:\Windows\TEMP\ffmpeg-passes59082e90450edzn2gy/pass-59082e90454d5" "D:\wamp\www\sell-a-video\storage\app/public\short_steve.mp4"
```

**Comment by daniyal92** [comment]
Unknown encoder 'libfaac'

**Comment by pascalbaljet** [comment]
That has to do with your FFMpeg build, try building it with support for ```libfaac``` or try a different audio codec:

```php
->inFormat(new \FFMpeg\Format\Video\X264('libfdk_aac'))
```

**Comment by daniyal92** [comment]
Alright yes it was an issue with the audio codec, 'libfdk_aac' didnt work either so i used 'libmp3lame' instead which seemed to work.

Thanks for the help.

**Comment by AmnaIqbal-01** [comment]
public function overlayCoordinates(Request $request)
{
    Log::info('Received request to overlay coordinates on video.');

    // Increase maximum execution time to handle video processing
    set_time_limit(300); // 300 seconds = 5 minutes

    try {
        // Validate the incoming request for video and coordinates text file
        $request->validate([
            'video' => 'required|file|mimes:mp4,avi,mkv,webm|max:102400', // Video max size 100MB
            'coordinates' => 'required|file|mimes:txt|max:5120', // Coordinates text file max size 5MB
        ]);

        // Retrieve the uploaded video and coordinates file
        $videoFile = $request->file('video');
        $coordinatesFile = $request->file('coordinates');

        // Define the path for the video to be processed
        $videoFilePath = $videoFile->getRealPath();
        $videoFileName = $videoFile->getClientOriginalName();

        // Move the video file to the desired location if needed
        $storedVideoPath = $videoFile->storeAs('public/videos', $videoFileName);

        // Open the video file using Laravel FFmpeg
        $media = FFMpeg::fromDisk('public')
                       ->open('videos/' . $videoFileName);

        // Get video duration
        $duration = $media->getDurationInSeconds();
        Log::info('duration of the video ' . $duration);


        // Read JSON data from the coordinates text file
        $coordinatesJson = file_get_contents($coordinatesFile->getPathname());
        $coordinatesArray = json_decode($coordinatesJson, true);

        $filterString = "";
        $frameRate = 30; // Assuming a frame rate of 30 fps

        for ($currentTime = 0; $currentTime < $duration; $currentTime++) {
            $frameIndex = intval($currentTime * $frameRate); // Convert current time to an index

            if (isset($coordinatesArray['graphics'][$frameIndex])) {
                foreach ($coordinatesArray['graphics'][$frameIndex]['kpts'] as $keypoint) {
                    $x = $keypoint['p'][0] * 1920; // Assuming full HD video
                    $y = $keypoint['p'][1] * 1080;

                    $startTime = $frameIndex / $frameRate;
                    $endTime = ($frameIndex + 1) / $frameRate;
                    Log::info('processing');

                    $filterString .= "drawbox=x={$x}:y={$y}:w=10:h=10:color=red@0.5:t=fill:enable='between(t,{$startTime},{$endTime})',";
                }
            }
        }

        $filterString = rtrim($filterString, ',');

        // Log::info('Generated Filter String: ' . $filterString);

        // Apply the filter string to the video
        $media->addFilter(function ($filters) use ($filterString) {
            $filters->custom("{$filterString}");
            Log::info('filter works ');

        });
 
        Log::info('out of the filter command');

        // Set the output filename to 'output_video.mp4'
        $filename = 'output_video.mp4';
        Log::info('filename , '. $filename);

        $destinationPath = 'videos/' . $filename;

        Log::info('destination , '. $destinationPath);


        // Export the video to a specific disk and directory
        $media->export()
              ->toDisk('public')
              ->inFormat(new \FFMpeg\Format\Video\X264('libmp3lame', 'libx264'))
              ->save($destinationPath)
              ->onProgress(function ($percentage) {
                  Log::info("Processing: {$percentage}% done");
              })
              ->onFailure(function ($error) {
                  Log::error('FFmpeg failed with error: ' . $error->getMessage());
              });

        return response()->json([
            'message' => 'Video processed successfully with overlays.',
            'path' => Storage::url($destinationPath)
        ]);
    } catch (\Exception $e) {
        Log::error('Overlay process failed: ' . $e->getMessage());
        return response()->json(['error' => 'Overlay process failed. Please check logs for details.'], 500);
    }
}


here's my code , but I am getting output error and that 

I don't understand why, also change 

              ->inFormat(new \FFMpeg\Format\Video\X264('libmp3lame'))
 command to arrc and others but didn't work
