### ISSUE TITLE
FFMpeg \ Exception \ ExecutableNotFoundException Unable to load FFProbe Previous exceptions Executable not found, proposed : avprobe, ffprobe (0)

### ISSUE THREAD

**Issue by vsfarooqkhan** [pascalbaljetmedia/laravel-ffmpeg#130]
PATH set .
Installation of laravel-ffmpeg  package done . 
Config file also set . 
All steps in [https://github.com/pascalbaljetmedia/laravel-ffmpeg/blob/master/README.md]( readme) done well .
Still getting the same error . 
Any help?

**Comment by coding-sunshine** [comment]
Did u find any solution to this? I am facing the same error

**Comment by pascalbaljet** [comment]
This has been asked many times: https://github.com/pascalbaljetmedia/laravel-ffmpeg/wiki/Unable-to-load-FFProbe
