### ISSUE TITLE
Faster way to encode videos

### ISSUE THREAD

**Issue by michaelaguiar** [pascalbaljetmedia/laravel-ffmpeg#133]
Is there a quicker way to encode videos to libx264?  I see FFMpeg has a preset for "ultrafast" - is there a way to set that in this package?

This is what I have now, but it seems to take quite a while

```php
$format = new \FFMpeg\Format\Video\X264('aac', 'libx264');
$video = FFMpeg::fromDisk('local')->open($path);
$video->export()->inFormat($format)->save($where . '/' . $file_name . '.mp4');
```

**Comment by pascalbaljet** [comment]
You can add arguments to your export:

```php
$video->addFilter('-preset', 'ultrafast');
```

It might be a little bit faster but H264 encoding is gonna take a while anyhow. Maybe you can try to get [QuickSync](https://trac.ffmpeg.org/wiki/Hardware/QuickSync) to work.

**Comment by michaelaguiar** [comment]
Oh nice. As for the encoding, is there a better format to use for displaying on web that may be faster?  I just need it to play the uploaded video on the site regardless of the format the original video is in. 

Thanks for the response!
