### ISSUE TITLE
error encoding .mov to x264

### ISSUE THREAD

**Issue by karelbyte** [pascalbaljetmedia/laravel-ffmpeg#134]
hello I'm trying to convert a video taken with iphone .mov and it returns a failed encoding error
this is the code that I am using
if I change to an encoder like webm if it works
some clue what is going on

 FFMpeg::fromDisk('public')
                        ->open($uid .'/videos/' . $name)
                        ->export()
                        ->inFormat(new X264())
                        ->toDisk('public')
                        ->save($uid .'/videos/' . $pureName . '.mp4');

**Comment by pascalbaljet** [comment]
https://github.com/pascalbaljetmedia/laravel-ffmpeg/wiki/FFmpeg-failed-to-execute-command
