### ISSUE TITLE
Class 'PbMedia\LaravelFFMpeg\FFMpegFacade' not found during unit test only

### ISSUE THREAD

**Issue by ludo237** [pascalbaljetmedia/laravel-ffmpeg#137]
Hello.

First of all thanks for this amazing package.

I would like to report an issue that I'm currently facing with a single test and it's really odd. I'll explain.

I've a job that creates a poster for any given video, the `handle` of this job is pretty simple

```PHP
 public function handle()
    {
        /** @var \Pbmedia\LaravelFFMpeg\Media $videoProcessor */
        $videoProcessor = FFMpeg::open($this->media->fullPath());
        
        $path = "{$this->media->file_name}/{$this->media->file_name}.jpg";
        
        // Create the poster
        $videoProcessor
            ->getFrameFromSeconds($videoProcessor->getDurationInSeconds() / 2)
            ->export()
            ->save($path);
    
        FFMpeg::cleanupTemporaryFiles();
    }
```

Basically it has a media object (a model nothing to worry about) that return the full path of the current active disk and then saves inside the same folder a new `jpg` image, simple stuff as I said.

The code itself works and it is currently in production and it does his job (pun intended)

The problem I'm facing is within the unit tests of this job class, here's the current broken code

```PHP
 public function it_create_a_poster_based_on_the_video()
    {
        Event::fake();
        
        $fileStub = new UploadedFile($this->getStub(), "first");
        $fileName = $fileStub->hashName();
        [$mediaName, $extension] = explode(".", $fileName);
        $fileStub->storePublicly($fileName);
        
        $media = factory(Media::class)->state("video")->create([
            "name" => $mediaName,
            "file_name" => $mediaName,
            "extension" => $extension,
        ]);
        
        $job = new CreatePoster($media);
        $job->handle();
        
        Storage::assertExists("{$fileName}/{$fileName}.jpg");
    }
```

Again the code here is not that hard, the test creates and upload a stub (a sample mp4 file) and then created an entity inside the database using the factories. Once it's ready it fires up the job explained above. The problem is that **only in this particular test** it throws the exception of 

    Class 'PbMedia\LaravelFFMpeg\FFMpegFacade' not found

Why? 😕 Am I Missing something? The `.env` file and `.env.testing` file are identical during development and no redis queue is used (in production queue is on and it works anyway)

**Comment by pascalbaljet** [comment]
The namespace is `Pbmedia`, not `PbMedia`, maybe that's the problem.

**Comment by ludo237** [comment]
O what a shame! It was that.

I don't get why despite the wrong namespace only the test was broken 🤔 anyway the namespace typo fix the problem
