### ISSUE TITLE
Encoding failed

### ISSUE THREAD

**Issue by adnanalidzinemedia** [pascalbaljetmedia/laravel-ffmpeg#140]
I have install this package and also install the ffmpeg on my windows and i am getting encoding failed issue can you please give me a clue to resolve this issue and wanted to decrease the size of the video by  adding filter to change the dimension and size of the video and want to store in the mp4 here is my function code below
```
public function convert_video()
    {


        $media = FFMpeg::fromDisk('local')
        ->open('song.mp4')
        ->addFilter(function ($filters) {
            $filters->resize(new \FFMpeg\Coordinate\Dimension(640, 480));
        })
        ->export()
        ->toDisk('local')
        ->inFormat(new \FFMpeg\Format\Video\X264)
        ->save('short_steve.mp4');
        // dd($media);
    }
```
please help me out
here is i think the issue is in the format x264 or something else. 
thanks in advance

**Comment by vasanthudhaya** [comment]
What you write in your code is ok, you missed the streams. Use the below line the issue get fixed. @adnanalidzinemedia 

` ->inFormat(new \FFMpeg\Format\Video\X264)`

Instead the above use the below line

`->inFormat(new \FFMpeg\Format\Video\X264('libmp3lame', 'libx264'))`

**Comment by hemantachhami19** [comment]
I am suffering from same problem .
 failed to execute command '/usr/bin/ffmpeg' '-y' '-i' '

**Comment by pascalbaljet** [comment]
https://github.com/pascalbaljetmedia/laravel-ffmpeg/wiki/FFmpeg-failed-to-execute-command
