### ISSUE TITLE
Hls Fast encode 

### ISSUE THREAD

**Issue by rapcrown** [pascalbaljetmedia/laravel-ffmpeg#144]
Hello,

I encode with the codes below but it is slow. How can I make it faster?

`  

    $lowBitrate = ( new X264 )->setKiloBitrate( 1000 )->setVideoCodec( 'libx264' )->setAudioCodec( "libmp3lame" )->setAdditionalParameters( [
            "-strict",
            "-2",
        ] );

 FFMpeg::fromDisk($this->video->disk)
            ->open("video/".$this->video->path)
            ->exportForHLS()
            ->setSegmentLength(10) // optional
            ->toDisk('public')
            ->addFormat($lowBitrate, function($media) {
                $media->addFilter(function ($filters) {
                    $filters->resize(new \FFMpeg\Coordinate\Dimension(640, 360));
                });
            })
            ->onProgress(function ($percentage) {
                $json_360p = json_encode(array('title' => "360P Render",'durum' => $percentage));
                islemsira::where('video_id','=',$this->video->id)->update(['durum' => $json_360p]);
            })
            ->save($video_360p_name);`

**Comment by pascalbaljet** [comment]
You could use the `-preset ultrafast` parameter but the quality of the encoding will decrease. Keep in mind that encoding video is a very CPU-intensive operation, also take a look a the 'threads' config (depending on your server specs).

**Comment by rapcrown** [comment]
> You could use the `-preset ultrafast` parameter but the quality of the encoding will decrease. Keep in mind that encoding video is a very CPU-intensive operation, also take a look a the 'threads' config (depending on your server specs).

Thank you.
