### ISSUE TITLE
 my percentage stucked in "99.666666666667"

### ISSUE THREAD

**Issue by Adamkaram** [pascalbaljetmedia/laravel-ffmpeg#145]
when i tried to upload a video  notice that percentage are stuck in  "99.666666666667"  and i don't know why , so  i'm copy codes from source code to this course and did it with ConvertForStreaming.php and same with channel-uploads.js   and try to upload a various  videos but same problem and in my php.ini try to edit some value to this as a try to it to make it  working but so bad to my luck and i'm desperate
what my codes lokks like:

  public function handle()
    {
      $low = (new X264('aac'))->setKiloBitrate(100);
      $med = (new X264('aac'))->setKiloBitrate(250);
      $high = (new X264('aac'))->setKiloBitrate(500);

      FFMpeg::fromDisk('local')
      ->open($this->video->path)
      ->exportForHLS()
      ->onProgress(function ($percentage) {
                $this->video->update([
                    'percentage' => $percentage,
                    Log::info('HLS export', compact('percentage'))
                ]);
            })

      ->addFormat( $low)
      ->addFormat($med)
      ->addFormat($high)
      ->save("public/videos/{$this->video->id}/{$this->video->id}.m3u8");
}
}

**Comment by Adamkaram** [comment]
trying to log percentage and i got this should this be an issue with package 


[2019-08-01 14:21:42] local.INFO: HLS export {"percentage":98.33333333333333} 
[2019-08-01 14:21:43] local.INFO: HLS export {"percentage":99.66666666666666} 
[2019-08-01 14:21:43] local.INFO: ffmpeg executed command successfully

**Comment by pascalbaljet** [comment]
So the exact problem is that the percentage doesn't hit 100%? Is the transcoding successful though?

**Comment by x2team** [comment]
I had the same problem. Please help me!

**Comment by pascalbaljet** [comment]
I've rewritten the package and this issue has been resolved. Could you test the `v7` branch? Almost no breaking changes except for some filter stuff in HLS exports.

https://github.com/pascalbaljetmedia/laravel-ffmpeg/tree/v7

`composer require "pbmedia/laravel-ffmpeg:v7.x-dev"`

**Comment by pascalbaljet** [comment]
Fixed in `v7.0`
