### ISSUE TITLE
Can't save HLS .ts format to S3

### ISSUE THREAD

**Issue by alexykouakou** [pascalbaljetmedia/laravel-ffmpeg#149]
I would save a HLS encoded Video to S3 
VIDEO IS ENCODED BUT **ONLY** .m3u8 file IS SAVED TO S3
**All .ts files are missing**
All works fine in local but with s3, only .m3u8 is saved

```
FFMpeg::open('my_movie.mov')
    ->exportForHLS()
    ->setSegmentLength(1) // optional
    ->addFormat($lowBitrate, function($location) {
            $start = \FFMpeg\Coordinate\Timecode::fromSeconds(1);
            $end = \FFMpeg\Coordinate\Timecode::fromSeconds(30);
            $clip = new \FFMpeg\Filters\Video\ClipFilter($start, $end);
            $location->addFilter($clip);
        })
    ->addFormat(...another format)
    ->toDisk('s3')
    ->save('my_movie.m3u8);
```

HI! and Thanks in advance for help!!

**Comment by alexykouakou** [comment]
ok, I see Issue 124
[](https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/124)

**Comment by alexykouakou** [comment]
ok, I see Issue 124
[https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/124](url)

**Comment by pascalbaljet** [comment]
HLS to a remote disk is unsupported at the moment but I'm working on a branch with this feature: https://github.com/pascalbaljetmedia/laravel-ffmpeg/tree/hls-external

Please continue the discussion in this topic: https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/124
