### ISSUE TITLE
Temporary Video Files

### ISSUE THREAD

**Issue by tuckerdarby** [pascalbaljetmedia/laravel-ffmpeg#15]
Hi Pascal,

I'm currently running this plugin on a small server with very little storage space and keep running into the issue of filling up storage. I've written a cron job to remove these files every few minutes, but it would be great if the plugin removed these files after they are used.

Since this use case is rather specific, maybe there could be a flag to tell the plugin whether to do this or not? Just a suggestion, but it would be a major help.

**Comment by pascalbaljet** [comment]
I've just tagged version 1.1.6 which has a new ’’’cleanupTemporaryFiles’’’ method. You can call this method (on the facade) after the export jobs are done.

**Comment by tuckerdarby** [comment]
That's fantastic! Thank you very much.
