### ISSUE TITLE
Make it a DeferrableProvider provider

### ISSUE THREAD

**Issue by tiran133** [pascalbaljetmedia/laravel-ffmpeg#151]
Can you make it a DeferrableProvider you hardly need this on any app load.

Or give me a reason on why it needs to be registered on every request?

Kind Regards
Alex

**Comment by pascalbaljet** [comment]
Thanks! Will look into it :)

**Comment by pascalbaljet** [comment]
I don't see the benefit of this as most stuff gets compiled and cached. If somebody would work on this and create a PR, I would merge it.
