### ISSUE TITLE
How to convert one file to multi res ?

### ISSUE THREAD

**Issue by mohsenbostan** [pascalbaljetmedia/laravel-ffmpeg#152]
Hey, I have a problem with converting files. I upload my files like this :
```
public function store(Request $request)  
{  
$video = Video::create(\[  
'disk' => 'public',  
'original\_name' => $request->video->getClientOriginalName(),  
'path' => Storage::put('public/videos', $request->file('video')),  
'title' => $request->title,  
\]);

return response()->json([
   'uploaded'
], 201);

}
```
But I don't know how to convert the theme to for example 720, 480, 144 ...
please give me a code. i read all docs but i could not found my solution.

**Comment by pascalbaljet** [comment]
Chaining exports is in the docs:
https://github.com/pascalbaljetmedia/laravel-ffmpeg#usage
