### ISSUE TITLE
After 5.0.1 and Laravel 6.1.0  composer ERRORS: Ambiguous class resolution, "FFMpeg\Coordinate\Aspect Ratio" 

### ISSUE THREAD

**Issue by ibrainventures** [pascalbaljetmedia/laravel-ffmpeg#153]
Hi,
thanks for this package,

i had before the Lara 6. and your package upgrade:
those two packages on our installation:

-        "php-ffmpeg/extras": "^0.3.1",
        "php-ffmpeg/php-ffmpeg": "^0.14.0",

now they are throwing the the ambiguos class resolution error because the
alchemy-binary package files are also inside your own vendor namespace.

What is actually the right way for the composer packages?

Thanks in advance ..

**Comment by pascalbaljet** [comment]
There are some dependency issues with the underlying library (mainly with Monolog 2). For the time being I patched it by swapping the dependencies. I did this before with the Symfony 4 upgrade, I don't think there a solid solution at the moment.
