### ISSUE TITLE
How I can add watermark to video using this package?

### ISSUE THREAD

**Issue by shahzadwaris** [pascalbaljetmedia/laravel-ffmpeg#155]

**Comment by pascalbaljet** [comment]
```php
FFMpeg::open('video.mp4')
    ->addFilter(function ($filters) use ($watermarkPath) {
        $filters->watermark($watermarkPath, [
            'position' => 'relative',
            'bottom' => 50,
            'right' => 50,
        ]);

        // or

        $filters->watermark($watermarkPath, [
            'position' => 'absolute',
            'x' => 1180,
            'y' => 620,
        ]);
    })
    ->export();
```

**Comment by shahzadwaris** [comment]
How to save the exported file and where does it save the file?

**Comment by shahzadwaris** [comment]
How does path work on windows I'm facing file not found issues. FFmpeg give me the error file not found as I'm using storage_path() function. Why this is happened?

**Comment by pascalbaljet** [comment]
> How to save the exported file and where does it save the file?

Please read the documentation.

**Comment by pascalbaljet** [comment]
> How does path work on windows I'm facing file not found issues. FFmpeg give me the error file not found as I'm using storage_path() function. Why this is happened?

Could you share a piece of code?

**Comment by Rohan2998** [comment]
i am getting an undefined variable error even though i am echoing it just before using it in the ffmpeg code the file location is right

here is my code

$watermarkPath = public_path('watermark.png');

        echo $watermarkPath;
        
        // open the uploaded video from the right disk...
        FFMpeg::fromDisk('original_path')
            ->open($this->video->path)
            // add the 'resize' filter...
            ->addFilter(function (VideoFilters $filters) {
                $filters->resize(new \FFMpeg\Coordinate\Dimension(960, 540));
                $filters->watermark($watermarkPath, [
                    'position' => 'relative',
                    'bottom' => 50,
                    'right' => 50,
                ]);
            })
            ->export() // call the 'export' method...
            ->onProgress(function ($percentage){
                echo "{$percentage}% transcoded";
            })
            ->inFormat(new \FFMpeg\Format\Video\X264('libmp3lame','libx264')) // tell the MediaExporter to which disk and in which format we want to export...
            ->toDisk('streaming_path')
            ->save($converted_name); // call the 'save' method with a filename...


this is the error i am getting 
ErrorException: Undefined variable: watermarkPath in C:\Users\Rohan\Downloads\TaandavFilmsAdminDashboard-master\TaandavFilmsAdminDashboard-master\app\Jobs\CompressUploadedVideo.php:53
Stack trace:
