### ISSUE TITLE
installation error in laravel 5.7

### ISSUE THREAD

**Issue by safiyaAkhtar06** [pascalbaljetmedia/laravel-ffmpeg#156]
i am getting this error while trying to install version 3.0.0 which is compatible with laravel 5.7
`
  Problem 1
    - Installation request for pbmedia/laravel-ffmpeg 3.0.0 -> satisfiable by pbmedia/laravel-ffmpeg[3.0.0].
    - pbmedia/laravel-ffmpeg 3.0.0 requires php-ffmpeg/php-ffmpeg dev-master#c11b79ab5b0174aa1a56c54c67491169e78a4c17 -> satisfiable by php-ffmpeg/php-ffmpeg[dev-master] but these conflict with your requirements or minimum-stability.`

can you please solve this issue for me

this is my project other packages
` "php": ">=7.2.19",
        "alaouy/youtube": "^2.2",
        "barryvdh/laravel-cors": "^0.11.1",
        "consoletvs/charts": "^6.5",
        "cyrildewit/eloquent-viewable": "^3.0",
        "devmarketer/easynav": "^1.0",
        "doctrine/dbal": "^2.6",
        "fideloper/proxy": "^4.0",
        "geoip2/geoip2": "^2.8",
        "intervention/image": "^2.4",
        "laravel/cashier": "~7.0",
        "laravel/cashier-braintree": "^3.1",
        "laravel/framework": "5.7.*",
        "laravel/passport": "^7.5",
        "laravel/socialite": "3.0.9",
        "laravel/tinker": "~1.0",
        "laravelcollective/html": "^5.5",
        "paypal/rest-api-sdk-php": "*",
        "pragmarx/tracker": "^3.2",
        "socialiteproviders/gitlab": "^3.1.0",
        "spatie/laravel-newsletter": "^4.2",
        "spatie/laravel-permission": "^2.31",
        "spatie/laravel-translatable": "^2.2",
        "stripe/stripe-php": "^5.8",
        "tzsk/payu": "^2.0",
        "pbmedia/laravel-ffmpeg":"3.0.0",
        "unicodeveloper/laravel-paystack": "^1.0",
        "yajra/laravel-datatables-oracle": "~5.0"`

**Comment by pascalbaljet** [comment]
Please try using 3.0.2, there was a dependency issue with 3.0.0. It might be useful to upgrade your Laravel version as well, 5.7 is not supported anymore.
