### ISSUE TITLE
Question: Resize output image

### ISSUE THREAD

**Issue by kossa** [pascalbaljetmedia/laravel-ffmpeg#16]
Hi,

Please I want to create thumbnail of video, and I want all thumbs are the same size, here is my code but it does not work :

```
FFMpeg::fromDisk('local')
            ->open('1.mp4')
            ->addFilter(function ($filters) {
                $filters->resize(new \FFMpeg\Coordinate\Dimension(100, 100));
            })
            ->getFrameFromSeconds(10)
            ->export()
            ->toDisk('local')
            ->save('1.png')
            
```

**Comment by pascalbaljet** [comment]
Call the '''getFrameFromSeconds''' before the '''addFilter''' method.

**Comment by kossa** [comment]
Thank you @pascalbaljet , now I get another error :
```
Call to undefined method FFMpeg\Filters\Frame\FrameFilters::resize()
```

My code is :
```
FFMpeg::fromDisk('local')
            ->open('1.mp4')
            ->getFrameFromSeconds(10)
           ->addFilter(function ($filters) {
                $filters->resize(new \FFMpeg\Coordinate\Dimension(100, 100));
            })
            ->export()
            ->toDisk('local')
            ->save('1.png')
```

**Comment by pascalbaljet** [comment]
The ```resize``` method is not supported on ```Frame``` objects by the [underlying package](https://github.com/PHP-FFMpeg/PHP-FFMpeg). I think you should export the thumbnail at full resolution and resize it later on, for example with this package:
https://github.com/spatie/laravel-glide

**Comment by kossa** [comment]
Ok I see, thank you

**Comment by michielst** [comment]
Not sure if this is still relevant or documented somewhere else but I was also looking for a way to do this.

Works like this:
```
FFMpeg::fromDisk($disk)
    ->open($fileName)
    ->getFrameFromSeconds($seconds)
    ->export()
    ->addFilter(function (FrameFilters $filters) {
        $filters->custom('scale=320:180');
    })
    ->toDisk($saveToDisk)
    ->save($saveAs);
```
