### ISSUE TITLE
Laravel ffmpeg generated MP4 file with audio codec libmp3lame, but no audio on IOS Devices

### ISSUE THREAD

**Issue by jerald-laury123** [pascalbaljetmedia/laravel-ffmpeg#160]
I am using ffmpeg to convert videos to mp4, if the video is in other format using this code below:

$ffmpeg_cnv = \FFMpeg\FFMpeg::create();
$format=new \FFMpeg\Format\Video\X264('libmp3lame', 'libx264');
$video_cnv = $ffmpeg_cnv->open($uploaded_video_path);
$video_cnv->save($format,public_path().'/uploads/video/'.$file_name_without_ext.'.mp4');

But the converted mp4 video is not working properly only on ios. On ios it is playing without audio.

**Comment by fadhiilrachman** [comment]
Works with me, you should change audio codec from libmp3lame to aac:
`$lowBitrateFormat = (new \FFMpeg\Format\Video\X264('aac', 'libx264'))->setKiloBitrate(500);`

**Comment by fadhiilrachman** [comment]
Works with me, you should change audio codec from `libmp3lame` to `aac`:

```php
$lowBitrateFormat = (new \FFMpeg\Format\Video\X264('aac', 'libx264'))->setKiloBitrate(500);
```

**Comment by fadhiilrachman** [comment]
Works with me, you should change audio codec from libmp3lame to aac:

```php
$format = new \FFMpeg\Format\Video\X264('aac', 'libx264');
```
