### ISSUE TITLE
Video Conversion  - Laravel 6   - Window Machine

### ISSUE THREAD

**Issue by chisumo2016** [pascalbaljetmedia/laravel-ffmpeg#161]
I am converting video and processing the queue, but the job failed . When I checked in the log file  [2019-12-01 16:02:03] local.ERROR: ffprobe failed to execute command C:\ffmpeg\bin\ffprobe.

This is how the config/laravel-ffmpeg.php 
return [
    'default_disk' => 'local',

    'ffmpeg' => [
       // 'binaries' => env('FFMPEG_BINARIES', 'ffmpeg'),
        'ffmpeg.binaries'  => 'C:/FFmpeg/bin/ffmpeg.exe',
        'threads' => 12,
    ],

    'ffprobe' => [
        //'binaries' => env('FFPROBE_BINARIES', 'ffprobe'),
        'ffprobe.binaries' => 'C:/FFmpeg/bin/ffprobe.exe',

    ],

**Comment by pascalbaljet** [comment]
You got the config keys wrong. Check out the default config file.
https://github.com/pascalbaljetmedia/laravel-ffmpeg/blob/master/config/laravel-ffmpeg.php
