### ISSUE TITLE
fromDisk crashes when local filesystem is missing

### ISSUE THREAD

**Issue by alexandreMesle** [pascalbaljetmedia/laravel-ffmpeg#162]
Hi everybody, 

First of all, thanks for this great package !

I have customized my filsystem.php a little too much, and I removed this :

```
        'local' => [
            'driver' => 'local',
            'root' => storage_path('app/local'),
        ],
```

Laravel keeps working well without this disk, and for instance `Storage::('temp')` works well. But laravel-ffmpeg does not find the disk when I type `FFMpeg::fromDisk("temp")`, the error displayed is 'Driver [] is not supported.'

The workaround is easy : just put the local disk back into filesystems.php. But this issue remains strange... Why does Laravel find the disk and laravel-ffmpeg does not ?

Is it a bug ? Or have I misuderstood something ?

**Comment by pascalbaljet** [comment]
I think you should update the `defaut_disk` in the config file:
https://github.com/pascalbaljetmedia/laravel-ffmpeg/blob/master/config/laravel-ffmpeg.php
