### ISSUE TITLE
encode failed

### ISSUE THREAD

**Issue by candivan** [pascalbaljetmedia/laravel-ffmpeg#164]
$video = new VideoService();
  $video->ConvertM3U8('v0new.mp4','v0new.m3u8');

class VideoService extends BaseService
{

    public function ConvertM3U8($from_file, $to_file)
    {

        $lowBitrate = (new X264('libmp3lame'))->setKiloBitrate(250);
        $midBitrate = (new X264('libmp3lame'))->setKiloBitrate(500);
        $highBitrate = (new X264('libmp3lame'))->setKiloBitrate(1000);

        try{
            FFMpeg::fromDisk('videos')
                ->open($from_file)
                ->exportForHLS()

                ->setSegmentLength(10) // optional
                ->addFormat($lowBitrate)
                ->addFormat($midBitrate)
                ->addFormat($highBitrate)
                ->toDisk('videos')
                ->inFormat(new X264('aac'))
                ->save($to_file);
        }catch (\Exception $e){
            Log::debug($e->getMessage());
        }

    }
}

ffmpeg failed to execute command '/usr/local/bin/ffmpeg' '-y' '-i' '/Users/zhangliang/mpwallet-backend/storage/videos/v0new.mp4' '-map' '0' '-flags' '-global_header' '-f' 'segment' '-segment_format' 'mpeg_ts' '-segment_list' '/Users/zhangliang/mpwallet-backend/storage/videos/v0new_250.m3u8' '-segment_time' '10' '-threads' '12' '-vcodec' 'libx264' '-acodec' 'libmp3lame' '-b:v' '250k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-strict' '-2' '-pass' '1' '-passlogfile' '/var/folders/rh/3xrx_7cs5md2q7xknzl59d_80000gn/T/ffmpeg-passes5e1b3ba299d73a2w7p/pass-5e1b3ba299e1a' '/Users/zhangliang/mpwallet-backend/storage/videos/v0new_250_%05d.ts'

**Comment by pascalbaljet** [comment]
https://github.com/pascalbaljetmedia/laravel-ffmpeg/wiki/FFmpeg-failed-to-execute-command

**Comment by candivan** [comment]
I have change audio codec to 'libmp3lame' and I think ffmpeg support libmp3lame


ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
built with Apple clang version 11.0.0 (clang-1100.0.33.16)
configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.0.1.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.0.1.jdk/Contents/Home/include/darwin -fno-stack-check' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
