### ISSUE TITLE
ffmpeg GPU support

### ISSUE THREAD

**Issue by ob1y2k** [pascalbaljetmedia/laravel-ffmpeg#165]
Hi guys,

is there a way for library to support GPU ffmpeg encoding ?

for example this is our ffmpeg commands that does gpu accelerated encoding :

`ffmpeg -vsync 0 -hwaccel cuvid -c:v h264_cuvid -i test.mov -c:v h264_nvenc -preset slow -movflags faststart -profile:v baseline -b:v 500K -vf "scale_npp=trunc(iw/2)*2:trunc(ih/2)*2" -crf 23 -c:a aac -strict experimental -ar 22050 test_gpu.mp4`

not sure if possible to extend FFmpeg:: commands to use it...

tnx

ob1

**Comment by pascalbaljet** [comment]
I've rewritten the package and this rewrite might support GPU encoding. I've not tested it myself, maybe you could give it a try and test the `v7` branch? Almost no breaking changes except for some filter stuff in HLS exports.

https://github.com/pascalbaljetmedia/laravel-ffmpeg/tree/v7

`composer require "pbmedia/laravel-ffmpeg:v7.x-dev"`

```php
<?php

$format = new \FFMpeg\Format\Video\X264('libfaac', 'h264_cuvid');
$format->setInitialParameters(['-vsync', 0, '-hwaccel', 'cuvid']);

FFMpeg::fromDisk('videos')
    ->open('steve_howe.mp4')
    ->export()
    ->toDisk('converted_videos')
    ->inFormat($format)
    ->save('small_steve.mkv');
```

**Comment by srloois** [comment]
`$format->setInitialParameters` not takes effect.

I had to override `$format->getInitialParameters` over composer with: 

```
"autoload": {
        "exclude-from-classmap": [
            "vendor\\php-ffmpeg\\php-ffmpeg\\src\\FFMpeg\\Media\\AdvancedMedia.php"
        ],
        "psr-4": {
            ...
            "FFMpeg\\Media\\": "app/Overrides/"
        }
    },
```

**Comment by alissonalberini** [comment]
> ```
> $format->setInitialParameters(['-vsync', 0, '-hwaccel', 'cuvid']);
> ```

Its work in HLS?
