### ISSUE TITLE
HLS from storage

### ISSUE THREAD

**Issue by jennsenr** [pascalbaljetmedia/laravel-ffmpeg#167]
The converted video can be seen if it is in public but not from storage with the URL method or with the GET method

```
       $video = Storage::disk('videos')->url($episode->video);

      return new Response($video, 200, ['Content-Type' => 'application/x-mpegURL']);
```

**Comment by pascalbaljet** [comment]
I don't think this is an issue with the package but rather a thing you have to implement yourself. You could use `Symfony\Component\HttpFoundation\StreamedResponse` to stream the contents from your storage, beware that you also need to implement headers like `Accept-Ranges`, `Content-Length` and `Content-Range`.
