### ISSUE TITLE
Get the format/size of the video

### ISSUE THREAD

**Issue by tahirafridi** [pascalbaljetmedia/laravel-ffmpeg#169]
I know it is a silly question, but I didn't find anyone asking it. Let me explain,
For example, I download a 720p video from YouTube and then I'm uploading that video to my system, how do I know that the video is already in the format 720p HD so I will not export it. or if I upload a video in very low quality like 360p then how do I know that it should not convert to upper versions like 480p or 720p.
For images, I can use the image intervention library to get the size fo the image and i will not resize the image if my condition met, but how to do it with videos in this library?

**Comment by pascalbaljet** [comment]
https://github.com/pascalbaljetmedia/laravel-ffmpeg/wiki/Get-the-dimensions-of-a-Video-file
