### ISSUE TITLE
Unable to make Directory

### ISSUE THREAD

**Issue by grappetite-tahir** [pascalbaljetmedia/laravel-ffmpeg#170]
As you described in the tutorial that you will have 3 disks, 1 is non public and other two will be public disks. So exactly the same I created the disks got name ideas from your Jobs files.

So now when I'm browsing a video and input the title, hitting submit button giving me this error https://prnt.sc/r0y1ui

I'm using MacBook and I have given proper permissions to the storage directory, can you please check what is the cause of the issue?

**Comment by pascalbaljet** [comment]
Can you share the full stack trace?

**Comment by grappetite-tahir** [comment]
Here is the content of the stack trace

` * {@inheritdoc}

     */

    public function getName()

    {

        return 'ffprobe';

    }

 

    /**

     * Creates an FFProbeDriver.

     *

     * @param array|ConfigurationInterface $configuration

     * @param LoggerInterface              $logger

     *

     * @return FFProbeDriver

     */

    public static function create($configuration, LoggerInterface $logger = null)

    {

        if (!$configuration instanceof ConfigurationInterface) {

            $configuration = new Configuration($configuration);

        }

 

        $binaries = $configuration->get('ffprobe.binaries', array('avprobe', 'ffprobe'));

 

        try {

            return static::load($binaries, $logger, $configuration);

        } catch (BinaryDriverExecutableNotFound $e) {

            throw new ExecutableNotFoundException('Unable to load FFProbe', $e->getCode(), $e);

        }

    }

}

 `

**Comment by grappetite-tahir** [comment]
Here is the complete stack trace and other details
https://flareapp.io/share/o7AKgxmp#F73

**Comment by pascalbaljet** [comment]
What is the result of ` sys_get_temp_dir()` on your machine? Do you have write permissions for that specific directory?

**Comment by grappetite-tahir** [comment]
i returned sys_get_temp_dir() in php and i got this output 
/var/folders/mn/3nv025hs4g16xt_spj91bhn80000gn/T

**Comment by grappetite-tahir** [comment]
From the terminal on the mac I tried this command chmod -R 755 /var/folders/mn/3nv025hs4g16xt_spj91bhn80000gn/T
it says 
Unable to change file mode on /var/folders/mn/3nv025hs4g16xt_spj91bhn80000gn/T: Operation not permitted

**Comment by pascalbaljet** [comment]
You need to edit the `sys_temp_dir` PHP configuration setting or fix the permission issue. This is not an issue with this package but with your local PHP configuration.
