### ISSUE TITLE
Server crashed due to crawded tmp folder

### ISSUE THREAD

**Issue by karla** [pascalbaljetmedia/laravel-ffmpeg#171]
Hello I have an issue after couple of months working with it, the tmp folder in server just crashed the server duo to the library creates lots of file while encoding process, the deal is after cleaning the tmp folder the encoding just stop working. do you have any clue about it, I am wonder if some files should stay in that folder. I will appreciate any help.
Thanks

**Comment by pascalbaljet** [comment]
You can run `FFMpeg::cleanupTemporaryFiles();` after finishing an export.
