### ISSUE TITLE
Freezes when using video concat

### ISSUE THREAD

**Issue by tnduc** [pascalbaljetmedia/laravel-ffmpeg#177]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | ^0.14 (laravel-ffmpeg)
| FFmpeg Version | ffmpeg version 2.8.15-0ubuntu0.16.04.1
| OS             |  Docker - Ubuntu

#### Actual Behavior

```
 $disk = FFMpeg::fromDisk('local');

  $pathVideos = [];

 foreach ($this->videos as $key => $video) {
    $pathVideos[$key] = $video->getPath();
  }

 $disk->open("{$this->videos[0]->id}/{$this->videos[0]->file_name}")
     ->concat($pathVideos)
     ->saveFromSameCodecs(storage_path('app/' .  $this->videos[0]->collection_name) . ".mp4", TRUE);

```

#### Expected Behavior

No freezing, output_video duration = total_video duration

#### Steps to Reproduce

Video demo output: https://streamable.com/hnuzyp

#### Possible Solutions

Is it related to the processor thread or amd chip?

**Comment by pascalbaljet** [comment]
This seems a FFmpeg issue. Could you share the logs?

**Comment by tnduc** [comment]
> This seems a FFmpeg issue. Could you share the logs?

I have solved the problem with `framerate()`, due to the different aspect ratios of videos.

**Comment by francoism90** [comment]
@tnduc I have the same issue, how did you fix it (also in the new version)?

It causes freezes when I concat.

**Comment by tnduc** [comment]
> [@tnduc](https://github.com/tnduc) I have the same issue, how did you fix it (also in the new version)?
> 
> It causes freezes when I concat.

I have solved the problem with framerate(), due to the different aspect ratios of videos.
