### ISSUE TITLE
Fatal Error!

### ISSUE THREAD

**Issue by aminyazdanpanah** [pascalbaljetmedia/laravel-ffmpeg#18]
Hi there,
First of all great library!
I use `use Pbmedia\LaravelFFMpeg\FFMpeg;` in my controller and use:

`$lowBitrate = (new X264)->setKiloBitrate(250);`
`$midBitrate = (new X264)->setKiloBitrate(500);`
`$highBitrate = (new X264)->setKiloBitrate(1000);`
`FFMpeg::fromDisk('videos')`
 ` ->open('steve_howe.mp4')
    ->exportForHLS()
    ->setSegmentLength(10) // optional
    ->addFormat($lowBitrate)
    ->addFormat($midBitrate)
    ->addFormat($highBitrate)
    ->save('adaptive_steve.m3u8'); `
 
in my method and then I got an error:
`ErrorException in mainController.php line 118:
Non-static method Pbmedia\LaravelFFMpeg\FFMpeg::fromDisk() should not be called statically`

In other hands, when I use `use FFMpeg\FFMpeg;` it says: 
`FatalThrowableError in mainController.php line 118:
Call to undefined method FFMpeg\FFMpeg::fromDisk()`

where'd I go wrong?

**Comment by pascalbaljet** [comment]
Use the facade instead of the `FFMpeg` class (see README and Laravel docs)

**Comment by oimken** [comment]
GOT it.. sorry about that......
