### ISSUE TITLE
mp3 export size is larger than expected

### ISSUE THREAD

**Issue by mohammad6006** [pascalbaljetmedia/laravel-ffmpeg#183]
for convert from FLAC to MP3 128
```
        $lowBitrateFormat = (new \FFMpeg\Format\Audio\Mp3)->setAudioKiloBitrate(128);
```
and export

```
            FFMpeg::fromDisk('audios_disk')->open($localpath)
            ->export()
            ->inFormat($lowBitrateFormat)
            ->save('test.mp3')
```
but converted audio file size is larger than expected
flac : 21 Mb

mp3 128: 6 Mb ( should be 3 Mb)

**Comment by pascalbaljet** [comment]
Mono to stereo maybe?

**Comment by mohammad6006** [comment]
I test this code on my server 
```
ffmpeg -i filename.flac -c:v copy -c:a libmp3lame -b:a 128k filename.mp3

```
it works good and low size
but i dont know how can i change my format code with c:c c:a b:a options
```
        $lowBitrateFormat = (new \FFMpeg\Format\Audio\Mp3)->setAudioKiloBitrate(128);
```

**Comment by pascalbaljet** [comment]
What is the length in minutes of the original FLAC file?

**Comment by mohammad6006** [comment]
@pascalbaljet I test it for length 30 Sec file and ~ 5 Min files

when I run this code manually everything is ok :
```
ffmpeg -i filename.flac -c:v copy -c:a libmp3lame -b:a 128k filename.mp3
```

but I cant use setvideocodec for audio files on codes

**Comment by pascalbaljet** [comment]
> @pascalbaljet I test it for length 30 Sec file and ~ 5 Min files

Can you be more specific? What is length of the FLAC file that 'should be 3MB' in 128kbps MP3?

**Comment by mohammad6006** [comment]
> > @pascalbaljet I test it for length 30 Sec file and ~ 5 Min files
> 
> Can you be more specific? What is length of the FLAC file that 'should be 3MB' in 128kbps MP3?

**Comment by mohammad6006** [comment]
I wrote FLAC size in the question

**Comment by mohammad6006** [comment]
this changes solved my problem :
```
->addFilter('-c:v', 'copy')
```
