### ISSUE TITLE
Trying to add loop on GIF watermark gives error 

### ISSUE THREAD

**Issue by swankey** [pascalbaljetmedia/laravel-ffmpeg#188]
I am adding gif watermark on a the video and it is giving me error No such filter: '-ignore_loop 0' when I am trying to add the loop in that GIF.

Here is the code I am using 

```
$customFilter = (' -ignore_loop 0 ');
addFilter(function ($filters) use ($watermarkPath) {
                        $filters->watermark($watermarkPath, [
                            'position' => 'absolute',
                            'bottom' => 300,
                            'right' => 100,
                            'scale=w' => 300,
                            'scale=h' => 200,
                        ]
                    );
                    })
->addFilter(function ($filters) use ($customFilter) {
                        $filters->custom( $customFilter );
                        
                 })
```

This is the output command 

`'/usr/local/bin/ffmpeg' '-y' '-i' '/Users/xfd/Documents/Projects/Test/storage/app/public/uploaded/AboruApZgJgf7faZ9mTAPBu5a2qn2w4ldWbosAdb.mp4' '-preset' 'ultrafast' '-threads' '12' '-vcodec' 'libx264' '-acodec' 'libmp3lame' '-b:v' '2500k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-vf' 'movie=/Users/xfd/Documents/Projects/Test/public/storage/img/vfilter/aruba_frame.gif [watermark];[in]-ignore_loop 0[p0];[p0][watermark] overlay=0:0 [out]' '-pass' '1' '-passlogfile' '/var/folders/pg/7b4c598j08nd4lcd6c2h4_zr0000gn/T/ffmpeg-passes5ec2fe304004fhdai8/pass-5ec2fe304026f' '/Users/xfd/Documents/Projects/Test/storage/app/public/7.mp4'`

Please let me know what I am doing wrong here.  Thank you 

edit:
I did try the method you suggested in docs, that also didn't work (doesn't loop the gif). 

`->addFilter('-ignore_loop', 0);`

**Comment by pascalbaljet** [comment]
The `-ignore_loop 0` should be added before the `-i` parameter. The current version of this package doesn't support that. I've rewritten the package (will be released in a few weeks) and you can already try it!

Could you test the `v7` branch? Almost no breaking changes except for some filter stuff in HLS exports. You can set these parameters on the `format` instance.

https://github.com/pascalbaljetmedia/laravel-ffmpeg/tree/v7

`composer require "pbmedia/laravel-ffmpeg:v7.x-dev"`

```php
<?php

$format = new X264;
$format->setInitialParameters(['-ignore_loop', 0]);
```

**Comment by swankey** [comment]
Thank you so much for your time. I did try the v7 and I am getting this error
`syntax error, unexpected 'Disk' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)` 
on this first line
```
$filter = FFMpeg::fromDisk('public') 
        ->open($this->video->path)
```
I haven't changed any of the code so far besides adding ignore loop here
```
$high = (new X264('aac'))->setKiloBitrate(1500)
        ->setInitialParameters(['-ignore_loop', 0]);
```

**Comment by pascalbaljet** [comment]
Could you share the full code and stack trace?

**Comment by swankey** [comment]
Laravel 7.11
PHP 7.4.6
Mysql
```
   $video = Video::create([
            'disk'          => 'public',
            'original_name' => $request->video->getClientOriginalName(),
            'path'          => $request->video->store('uploaded', 'public'),
            'title'         => $request->title,
        ]);

        $this->video = $video;
        $high = (new X264('aac'))->setKiloBitrate(1500);
        // $lowBitrateFormat = (new X264('libmp3lame', 'libx264'))->setKiloBitrate(2500);
        $watermarkPath = public_path('storage/img/vfilter/test.gif');
        //  $customFilter = (" -ignore_loop  0 ");
       
                
        $filter = FFMpeg::fromDisk($this->video->disk) 
        ->open($this->video->path)
                     ->addFilter('-preset', 'ultrafast')
                     ->setInitialParameters(['-ignore_loop', 0])
                     ->addFilter(function ($filters) use ($watermarkPath) {
                        $filters->watermark($watermarkPath, [
                            'position' => 'absolute',
                            'bottom' => 50,
                            'right' => 0,
                            'scale=w' => 300,
                            'scale=h' => 200,
                        ]
                    );
                    })
                    ->addFilter(function ($filters) use($customFilter) {
                        $filters->custom($customFilter);
                 })
                    ->export()
                     ->toDisk('public') 
                     ->inFormat($high)
                    
                    ->save($this->video->id . '.mp4');

                    $this->video->update([
                        'converted_for_streaming_at' => Carbon::now(),
                    ]);

                    
        $streamUrl = Storage::disk('public')->url($video->id . '.mp4');
     

        return redirect('/newhome')
            ->with('status', $streamUrl);

    }
```

**Comment by swankey** [comment]
@pascalbaljet Sorry to bother you but wanted to ask if you managed to look into it. Thank you.

**Comment by swankey** [comment]
> Could you share the full code and stack trace?

Sorry didn't understand before. 
https://flareapp.io/share/dmk36bm3#F1

**Comment by pascalbaljet** [comment]
According to the Flare error, you're running PHP 7.2. `v7` is PHP 7.4 only.

**Comment by swankey** [comment]
That's weird, my cli shows php7.4. I checked vs it shows 7.2, let me correct that and try.

**Comment by swankey** [comment]
> According to the Flare error, you're running PHP 7.2. `v7` is PHP 7.4 only.

Here is the error I am getting
`Call to undefined method Pbmedia\LaravelFFMpeg\MediaOpener::setInitialParameters()

**Comment by pascalbaljet** [comment]
You need to call `setInitialParameters` on the format, not on the FFMpeg facade or `MediaOpener` instance. See https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/188#issuecomment-630628570

**Comment by swankey** [comment]
LOG.error: ffmpeg failed to execute command

`'/usr/local/bin/ffmpeg' '-y' '-ignore_loop' '0' '-i' '/Users/xyz/Documents/Projects/test/storage/app/public/uploaded/ldgiEAPPZdGuOdEnVgkJpKG9SCk5n4rCqZtBT9qH.mp4' '-preset' 'ultrafast' '-ignore_loop' '0' '-threads' '12' '-vcodec' 'libx264' '-acodec' 'aac' '-b:v' '1500k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-vf' 'movie=/Users/xyz/Documents/Projects/test/public/storage/img/vfilter/test-filter.gif [watermark];[in]scale=1080:1920 [p0];[p0][watermark] overlay=1:main_h - 1 - overlay_h [out]' '-pass' '1' '-passlogfile' '/var/folders/pg/7b4c598j08nd4lcd6c2h4_zr0000gn/T/ffmpeg-passes5edffcade9229yb201/pass-5edffcade92f4' '/Users/pradeep/Documents/Projects/AllLaravel/storage/app/public/46.mp4': ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.3 (clang-1103.0.32.59)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_3 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags=-fno-stack-check --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Option ignore_loop not found.
`
Feel free to close it because I have finished the project sorta. But if there is a work around for this I will keep a look out. 
Thank you for all your help and work.

**Comment by pascalbaljet** [comment]
`ignore_loop` only works with a `GIF`, both your input and output are `MP4`.

**Comment by swankey** [comment]
> I think `ignore_loop` only works with a `GIF`, both your input and output are `MP4`.

I actually ran the command directly on console and it works. Below is the cmd I used

`ffmpeg -y -i test-video.mp4 -ignore_loop 0 -i test-filter.gif -filter_complex "[1:v]scale=1080:1920[ovrl];[0:v][ovrl]overlay=0:0" -frames:v 900 -codec:a copy -codec:v libx264 -max_muxing_queue_size 2048 output.mp4`
