### ISSUE TITLE
Is there any way that I can speed up the ffmpeg processing time

### ISSUE THREAD

**Issue by Ahmedh96** [pascalbaljetmedia/laravel-ffmpeg#189]
I am facing a problem with the processing process. I use a real joint server in a digital hosting package of $ 10 and use cloud service from Amazon s3. The problem is when uploading a video, whatever the size of the video, whether its size is 1 megabyte or 2 Giga. After the upload process, the processing process starts to upload, there is no problem But when the processing process takes a very long time so that I cannot complete it, what is the solution to that, is there a problem for me or is this process normal?

**Comment by pascalbaljet** [comment]
Video transcoding is very CPU intensive, you just need raw CPU power and there's no way this package could ever increase the speed. 

Are you running the FFMpeg processing as a queued job? That might be a workaround. I wrote about it in this blogpost: https://protone.media/en/blog/how-to-use-ffmpeg-in-your-laravel-projects
