### ISSUE TITLE
Implement HLS with a key

### ISSUE THREAD

**Issue by aminyazdanpanah** [pascalbaljetmedia/laravel-ffmpeg#19]
Hi,
Is there any way to implement HLS with a **key** using this library?
My ffmpeg command is here:

> ffmpeg -y -i demo.mp4 -hls_time 9 -hls_key_info_file enc.keyinfo -hls_segment_filename "segmentedfile%d.ts" video.m3u8

**Comment by pascalbaljet** [comment]
You could use a `SimpleFilter` object for that but it's not in the scope of this project.

```php
use FFMpeg\Filters\Audio\SimpleFilter;

$media->addFilter(new SimpleFilter([
    '-hls_time', 9, 'etc..',
]))->export()->save('video.m3u8');
```

**Comment by pascalbaljet** [comment]
It's been a while, but for future visitors of this issue: v7.5 supports encrypted HLS.
