### ISSUE TITLE
Video clip from videos

### ISSUE THREAD

**Issue by videositefree** [pascalbaljetmedia/laravel-ffmpeg#190]
Hi,
I have problem with create clip from videos 

my code 
`            $start = \FFMpeg\Coordinate\TimeCode::fromSeconds(5);
            $clipFilter = new \FFMpeg\Filters\Video\ClipFilter($start);

            FFMpeg::fromDisk('local')
                ->open($ur)
                ->addFilter($clipFilter)
                ->export()
                ->toDisk('thumbnail')
                ->inFormat(new \FFMpeg\Format\Video\X264)
                ->save('test.mp4');`

and i have error
Error
Call to a member function toSeconds() on null 

                    foreach ($filters as $filter) {

                        if ($filter instanceof ClipFilter) {

 ->> here is error                         $duration = $filter->getDuration()->toSeconds();

                            break;

                        }

                    }
how to solve a problem? and is it a way to define start time in this way 00:00:15?

**Comment by pascalbaljet** [comment]
Unfortunately, this an issue with the [underlying library](https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/566).
