### ISSUE TITLE
custom_filter filter is not supported windows 10

### ISSUE THREAD

**Issue by swaraasolutions** [pascalbaljetmedia/laravel-ffmpeg#193]
Hi,

Thanks for the excellent package for managing FFMPEG.

There seems to be an issue with the new version when trying to scale
following error message comes up

`custom_filter filter is supported starting from 0.3 ffmpeg version; your ffmpeg version is N-92505-gce0a753634`

` FFMpeg::fromDisk("videos")->open($this->video->video_path)
->exportForHLS()
->setSegmentLength(10) // optional
->addFormat($lowBitrate, function ($media) {
                    $media->addFilter('scale=640:480');
                })`

**Comment by swaraasolutions** [comment]
Seems the above is resolved by switching to latest FFMPEG version

however there seems to be another error that is occuring

`Return value of ProtoneMedia\LaravelFFMpeg\Exporters\HLSPlaylistGenerator::getPathOfFirstSegment() must be of the type string, null returned`

Which seems to be fixed when changing he explode splitter to "\n" instead of "\r\n" (PHP_EOL for windows is "\r\n"

let me know if i can send a pull request to fix this.

**Comment by pascalbaljet** [comment]
I've created a branch with a fix, could you try it and report if it's working?
`composer require "pbmedia/laravel-ffmpeg:v7-windows-newline-fix-dev"`

**Comment by swaraasolutions** [comment]
Hi Thanks for blazing fast response. 
Looks like it's working now. 
Are you planning to merge this to release?

**Comment by pascalbaljet** [comment]
I just tagged 7.0.1 with the bugfix :)
