### ISSUE TITLE
Missing method to empty media collection

### ISSUE THREAD

**Issue by fabamb** [pascalbaljetmedia/laravel-ffmpeg#197]
Withe the new implementation of facade (MediaOpener) every time you use FFMpeg::open it adds a media to inernal collection ... with side effect

there is not a method to clear the collection so image to use of FFMpeg facade in a loop

A workaroud is FFMpeg::get()->shift(); but I don't like to  access (directly) to underlying structure 
especially if declared private, otherwise why not make it public?

**Comment by pascalbaljet** [comment]
Fixed in v7.0.3, this brings back the previous behavior of the facade.
