### ISSUE TITLE
Problems with watermark filter

### ISSUE THREAD

**Issue by MarwenSami** [pascalbaljetmedia/laravel-ffmpeg#20]
Hello,

I would like to add a watermark on a video, why should I add ->format() before saving? is it possible to keep the original format of the input video?
When I choose WebM the video get cropped to less than 1s.
How can I change the time of appearing and disappearing of the watermark? Should I create a custom filter?

Thank you.

**Comment by pascalbaljet** [comment]
I'll look into this problem next week!

**Comment by pascalbaljet** [comment]
The `save` method of the [underlying package](https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/master/src/FFMpeg/Media/Video.php#L62) requires a `FormatInterface`. You can try to  recreate the format of the original video. 

Custom filters are supported through the `SimpleFilter` object:

```php
use FFMpeg\Filters\Audio\SimpleFilter;

$media->addFilter(new SimpleFilter([
    '-hls_time', 9, 'etc..',
]))->export()->save('video.m3u8');
```
