### ISSUE TITLE
cut and resize video

### ISSUE THREAD

**Issue by videositefree** [pascalbaljetmedia/laravel-ffmpeg#202]
Hello,
How resize video i have 
code

`           $ffmpeg = \FFMpeg\FFMpeg::create();
            $video = $ffmpeg->open($url);
            $video->filters()->clip(\FFMpeg\Coordinate\TimeCode::fromSeconds($time_sec), \FFMpeg\Coordinate\TimeCode::fromSeconds(15));
            $video->save(new \FFMpeg\Format\Video\X264('libmp3lame'), '../../filmy/short/'.$last_id.'.mp4');`
and how add resize video

`->addFilter(function (VideoFilters $filters) {
        $filters->resize(new \FFMpeg\Coordinate\Dimension(640, 480));`?

**Comment by pascalbaljet** [comment]
Please read [the docs](https://github.com/pascalbaljetmedia/laravel-ffmpeg#filters) about filters, that's not how to add a filter.

**Comment by videositefree** [comment]
if you want to add a filter, an error appears, I don't know why

         FFMpeg::fromDisk('thumbnail')
            ->addFilter(function ($filters) use ($url) {
                $filters->watermark("testtsetst", [
                    'position' => 'relative',
                    'bottom' => 50,
                    'right' => 50,
                    'color' => 'white',
                ]);
            })
            ->save(''.$id.'aaa3333a.png');

Call to undefined method Pbmedia\LaravelFFMpeg\FFMpeg::addFilter() 

in controller i`have use Pbmedia\LaravelFFMpeg\FFMpegFacade as FFMpeg;
if delete this show error

Class 'App\Http\Controllers\FFMpeg' not found
