### ISSUE TITLE
change audio codec

### ISSUE THREAD

**Issue by vahidzoli** [pascalbaljetmedia/laravel-ffmpeg#205]
Here is my code:
```
$format = new X264('aac', 'libx264');
$format->setKiloBitrate(500);
```
but when videos transcode with `pascalbaljetmedia/laravel-ffmpeg`, this package sets audio codec to `mp3` by default instead `aac`.

How solve this problem?

**Comment by pascalbaljet** [comment]
Could you share your complete code that is related to FFMpeg?

**Comment by vahidzoli** [comment]
// create a video format...
        $format = new X264();
        $format->setAudioCodec("aac")->setKiloBitrate($this->parameters['bitrate']);

        $converted_name = $this->getCleanFileName($this->video->video);

        // open the uploaded video from the right disk...
        FFMpeg::fromDisk('videos')
            ->open($this->video->video_source)

            // add the 'resize' filter...

            ->addFilter(function ($filters) {
                $filters->resize(new Dimension($this->parameters['width'], $this->parameters['height']));
            })

            // call the 'export' method...
            ->export()

            // tell the MediaExporter to which disk and in which format we want to export...
            ->toDisk($this->path)//downloadable|downloadable_episode
            ->inFormat($format)

            // call the 'save' method with a filename...
            ->save($converted_name);

**Comment by vahidzoli** [comment]
my code works on local very well but when using that on server change audio format to libmp3lame by default!!!

**Comment by pascalbaljet** [comment]
Well that indicates your environments are not in sync. This is not an issue related to this package but rather related to your FFMpeg builds or environment configs.
