### ISSUE TITLE
Unable to load FFMpeg

### ISSUE THREAD

**Issue by Sohomcn** [pascalbaljetmedia/laravel-ffmpeg#206]
FFMpeg\Exception\ExecutableNotFoundException
Unable to load FFMpeg

vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFMpegDriver.php:55

LARAVEL 7

**Comment by pascalbaljet** [comment]
https://github.com/pascalbaljetmedia/laravel-ffmpeg/wiki/Unable-to-load-FFProbe
