### ISSUE TITLE
Generate preview from video

### ISSUE THREAD

**Issue by shanka12** [pascalbaljetmedia/laravel-ffmpeg#207]
How can I make a small preview from a video. When we mouse over on player, I want to show the small jpeg/Gif preview.
similar to this
https://www.binpress.com/generate-video-previews-ffmpeg/ 
or
https://github.com/transitive-bullshit/ffmpeg-generate-video-preview

**Comment by pascalbaljet** [comment]
You could exporting a number of frames using [a loop](https://github.com/pascalbaljetmedia/laravel-ffmpeg#multiple-exports-using-loops) and then use the [timelapse feature](https://github.com/pascalbaljetmedia/laravel-ffmpeg#create-a-timelapse) to generate a new video. This is not really an issue or bug, so I'll close this.
