### ISSUE TITLE
'Call to a member function videos() on array' when getting video dimensions

### ISSUE THREAD

**Issue by tbclla** [pascalbaljetmedia/laravel-ffmpeg#208]
The wiki on how to [get dimensions of a video](https://github.com/pascalbaljetmedia/laravel-ffmpeg/wiki/Get-the-dimensions-of-a-Video-file) currently gives the following example:

```php
FFMpeg::open('video.mp4')
    ->getStreams()
    ->videos()
    ->first()
    ->getDimensions();
```

However the `getStreams()` method always returns an array instead of a `FFMpeg\FFProbe\DataMapping\StreamCollection`, resulting in 'call to a member function videos() on array' error.

If this is indeed the intended behaviour then the wiki should be updated to use the `ProtoneMedia\LaravelFFMpeg\Drivers\PHPFFMPEG::getVideoStream()` method instead:

```php
FFMpeg::open('video.mp4')
    ->getVideoStream()
    ->getDimensions();
```

**Comment by pascalbaljet** [comment]
Thanks for the heads-up! I haven't updated the wiki yet :)
