### ISSUE TITLE
Lossless encoding of video files using this package

### ISSUE THREAD

**Issue by Desory** [pascalbaljetmedia/laravel-ffmpeg#209]
Hello there, first of all thanks for this package. Ive been on this topic for roundabout a week in search for the optimal encoding settings. What i want is simple: Achieve a size-reducted quality-lossless (or almost) video conversion. Could you give me any kind of hint as how to achieve this? I have been trying to mess with the kilobitrate (format mp4 to webm) and the codecs but my output file is always bigger than the input file in size.

`$bitrate = (new WebM())->setKiloBitrate(750);`

`        FFMpeg::fromDisk('spaces')
            ->open($filepath)
            ->export()
            ->toDisk('videos')
            ->inFormat($bitrate)
            ->save($name . '.webm');`

so thats what i got so far. Any help is appreciated.

Optimal would be if i could achieve this one here in laravel code, but i'm kinda lost

`ffmpeg -i input.mov -vcodec libvpx-vp9 -b:v 1M -acodec libvorbis output.webm`
thank you in advance

**Comment by pascalbaljet** [comment]
What's the bitrate and codec of your input file?
