### ISSUE TITLE
Path is wrong

### ISSUE THREAD

**Issue by chantrea** [pascalbaljetmedia/laravel-ffmpeg#21]
I by pass method fromDisk then it gave me the default path
but I used direct path from php file upload where /tmp/phpSLe9Ds something like that
but the object give me the laravel path /storage/app/tmp/phpSq8NxI which is not correct path it should be /tmp/phpSq8NxI

**Comment by pascalbaljet** [comment]
Could you provide some of your code? You probably need to create a local disk with no root (in your filesystem config file).

**Comment by chantrea** [comment]
Here is my code in Laravel 5.4
$uploadedFile = $request->file('post_video_upload');
            $timestamp = date('YmdHis');
            FFMpeg::open($uploadedFile->getRealPath())
	            ->addFilter(function ($filters) {
	            	$filters->resize(new \FFMpeg\Coordinate\Dimension(640, 480));
	            })
	            // export to FTP, converted in WMV
	            ->export()
	            ->toDisk('s3')
	            ->inFormat(new \FFMpeg\Format\Video\WMV)
	            ->save('users/videos/'.$timestamp."wmv")
            	// export to Amazon S3, converted in X264
	            ->export()
	            ->inFormat(new \FFMpeg\Format\Video\X264)
	            ->save('users/videos/'.$timestamp."mp4")
	            ->export()
	            ->inFormat(new \FFMpeg\Format\Video\WebM)
	            ->save('users/videos/'.$timestamp."webm")
	        ;

**Comment by pascalbaljet** [comment]
Alright, try this: 

Add a local disk to your `filesystems.php` config file:

```php

<?php

return [
    ...
    'disks' => [
        'local_root' => [
            'driver' => 'local',
            'root'   => '/',
        ],
        ...
    ],
    ...
];
```

Then open the uploaded file from the `local_root` disk:

```php
<?php

FFMpeg::fromDisk('local_root')
    ->open($uploadedFile->getRealPath())
    ->etc(...);
```

**Comment by chantrea** [comment]
Wow Awesome thank you so much. Let me try and I will let you know.

Thank you

**Comment by chantrea** [comment]
Having another issue 

Undefined index: extension
--
in File.php (line 29)
at HandleExceptions->handleError(8, 'Undefined index: extension', '/var/www/html/dev/vendor/pbmedia/laravel-ffmpeg/src/File.php', 29, array())in File.php (line 29)
at File->getExtension()in MediaExporter.php (line 79)
at MediaExporter->getDestinationPathForSaving(object(File))in MediaExporter.php (line 56)

**Comment by pascalbaljet** [comment]
Could you try to save it to a local disk to see if the previous problem has been fixed?

**Comment by chantrea** [comment]
After I save to local disks

Encoding failed
--
in Video.php (line 228)
at Video->save(object(X264), '/var/www/html/dev/public/chat/writable/videos/20170712051051.mp4')
at call_user_func_array(array(object(Video), 'save'), array(object(X264), '/var/www/html/dev/public/chat/writable/videos/20170712051051.mp4'))in Media.php (line 132)
at Media->__call('save', array(object(X264), '/var/www/html/dev/public/chat/writable/videos/20170712051051.mp4'))in MediaExporter.php (line 98)
at MediaExporter->saveAudioOrVideo('/var/www/html/dev/public/chat/writable/videos/20170712051051.mp4')in MediaExporter.php (line 60)
at MediaExporter->save('var/www/html/dev/public/chat/writable/videos/20170712051051.mp4')in TimelineController.php (line 507)
at TimelineController->createPost(object(Request))
at call_user_func_array(array(object(TimelineController), 'createPost'), array(object(Request)))in Controller.php (line 55)
at Controller->callAction('createPost', array(object(Request)))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(TimelineController), 'createPost')in Route.php (line 203)
at Route->runController()in Route.php (line 160)

**Comment by chantrea** [comment]
When I tried to save on local disk here is the error
at Video->save(object(X264), '//var/www/html/dev/storage/uploads/users/videos/20170712050030.mp4')
--
at call_user_func_array(array(object(Video), 'save'), array(object(X264), '//var/www/html/dev/storage/uploads/users/videos/20170712050030.mp4'))in Media.php (line 132)
at Media->__call('save', array(object(X264), '//var/www/html/dev/storage/uploads/users/videos/20170712050030.mp4'))in MediaExporter.php (line 98)
at MediaExporter->saveAudioOrVideo('//var/www/html/dev/storage/uploads/users/videos/20170712050030.mp4')in MediaExporter.php (line 60)
at MediaExporter->save('/var/www/html/friend7.com/dev/storage/uploads/users/videos/20170712050030.mp4')in TimelineController.php (line 507)
