### ISSUE TITLE
MP3 chapters

### ISSUE THREAD

**Issue by benrolfe** [pascalbaljetmedia/laravel-ffmpeg#210]
Does this package offer the ability to add chapters to mp3 files?

I see in the ffmpeg documentation that metadata can be added: https://ffmpeg.org/ffmpeg-formats.html#Metadata-1

Thanks!

**Comment by pascalbaljet** [comment]
You could probably do this by using a set of custom filters ([docs](https://github.com/pascalbaljetmedia/laravel-ffmpeg#custom-filters)):

```php
$metadataPath = '/full/path.txt';

FFMpeg::open('yesterday.mp3')
    ->addFilters('-i', $metadataPath, '-map_metadata', 1)
    ->export(...);
```
