### ISSUE TITLE
How to get Highest possible bit-rate  of a video

### ISSUE THREAD

**Issue by rabichawila** [pascalbaljetmedia/laravel-ffmpeg#211]
i want to create an HLS playlist for video streaming.
but  first  i want to check the video bit-rate or width/height to see if it's a 4k, 1080, 720 etc.

Here is what i want to do after getting the video information:
~~~

//check if we can make 4k version
if ( ( $bitrate >= 14000 )  ||  ( $width >= 3840 && $height >= 2160 ) ) 
{
     // Then it's a 4k video
    // We make a 4k version of HLS

}


//check if we can make HD version
if(  ( $bitrate >= 5800 )  ||  ( $width >= 1920 && $height >= 1080 )  )

{
     // Then it's a HD video
    // We make a HD version of HLS

}


//check if we can make 720 version
if(  ( $bitrate >= 3500 )  ||  ( $width >= 1280 && $height >= 720 )  )
{

...

~~~

Any help?.

**Comment by pascalbaljet** [comment]
```php
$media = FFMpeg::open('video.mp4');

$bitrate = $media->getFormat()->get('bit_rate');

$dimensions =$media->getVideoStream()->getDimensions();
```

See also [this wiki post](https://github.com/pascalbaljetmedia/laravel-ffmpeg/wiki/Get-the-dimensions-of-a-Video-file) and the [HLSPlaylistGenerator](https://github.com/pascalbaljetmedia/laravel-ffmpeg/blob/master/src/Exporters/HLSPlaylistGenerator.php#L28).
