### ISSUE TITLE
X265 and 360 degree

### ISSUE THREAD

**Issue by vahidzoli** [pascalbaljetmedia/laravel-ffmpeg#214]
hi,i used this package in my project and it's work very well.
but i want to know,does it support x265 video encode?
does it change simple video to 360 degree video??

**Comment by pascalbaljet** [comment]
You need to create your own video format class with the `libx265` encoder. Check out the `FFMpeg\Format\Video\X264` class on how to do this. Make sure you're running a build of FFmpeg [with support for H265](https://trac.ffmpeg.org/wiki/Encode/H.265).

Not sure what you mean with 'change simple video to 360 degree video'.
