### ISSUE TITLE
How to simply convert video files (i.e.: Avi to MP4)?

### ISSUE THREAD

**Issue by videositefree** [pascalbaljetmedia/laravel-ffmpeg#215]
Hi,
I simply want to convert files, any format to any format (at the moment, I need to convert AVI to MP4-h264 AND MP4-h264 to AVI), without losing quality. I don't want to resize (scale) the video, I don't want to change its aspect ratio and I don't want it to lose quality (this is very important); all I want is "to change the format", that's all. I found this code for only ffmpeg

"ffmpeg -i 1.mkv -codec copy 2.mp4"

Is there a similar way in ffmpeg laravel?

I am currently using
 "
   FFMpeg::fromDisk('local')
            ->open($path)
            ->export()
            ->inFormat(new \FFMpeg\Format\Video\X264('libmp3lame', 'libx264'))
            ->toDisk('convert_video')            
            ->save('$name.mp4');
"
 but it takes too long

Does ffmpeg laravel have a format for avi?

**Comment by pascalbaljet** [comment]
I just tagged v7.0.5 which has a `CopyFormat` class: https://github.com/pascalbaljetmedia/laravel-ffmpeg#export-without-transcoding
