### ISSUE TITLE
Non Static Method Errors

### ISSUE THREAD

**Issue by chantrea** [pascalbaljetmedia/laravel-ffmpeg#23]
Non-static method Pbmedia\LaravelFFMpeg\FFMpeg::fromDisk() should not be called statically
FFMpeg::fromDisk('local_root')->open($uploadedFile->getRealPath())
            ->addFilter(function ($filters) {
            	$filters->resize(new \FFMpeg\Coordinate\Dimension(640, 480));
            })
            ->export()
            ->toDisk('s3')
            ->inFormat(new \FFMpeg\Format\Video\WMV)
            ->save('users/videos/'.$filename.".wmv")
            // export to Amazon S3, converted in X264
            ->export()
            ->inFormat(new \FFMpeg\Format\Video\X264)
            ->save('users/videos/'.$filename.".mp4")
            ->export()
            ->inFormat(new \FFMpeg\Format\Video\WebM)
            ->save('users/videos/'.$filename.".webm")
            ;

**Comment by pascalbaljet** [comment]
https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/7
