### ISSUE TITLE
Example app?

### ISSUE THREAD

**Issue by wowcut** [pascalbaljetmedia/laravel-ffmpeg#26]
is there any chance of studying an example app made with this project to better understand the details of an implementation? Thanks for your attention!

**Comment by pascalbaljet** [comment]
There are a lot of examples in the README file, what do you want to know that's not in there?

**Comment by wowcut** [comment]
I see a few isolated code examples in the README.md, but it is not clear where to put these in the Laravel app context - also integration with e.g. an uploader would be interesting to see. Just some real world usage examples to better understand how to use this with Laravel. Thanks for your quick answer!

**Comment by pascalbaljet** [comment]
Alright I'll write a blogpost with some examples, maybe next week :)

**Comment by wowcut** [comment]
This is great news, thank you very much! When I am in Amsterdam, I will remember that I owe you a dinner :)

**Comment by pascalbaljet** [comment]
Here it is! https://pascalbaljetmedia.com/en/blog/how-to-use-ffmpeg-in-your-laravel-projects
