### ISSUE TITLE
(1/1) FatalThrowableError Call to undefined method FFMpeg\FFMpeg::fromDisk()

### ISSUE THREAD

**Issue by blu94** [pascalbaljetmedia/laravel-ffmpeg#28]
here is my code, i'm using laravel to build the application
```
use FFMpeg\FFMpeg;
use FFMpeg\FFProbe;

FFMpeg::fromDisk('vidpuz')
        ->open($export_as)
        ->getFrameFromSeconds(10)
        ->export()
        ->toDisk('thumnails')
        ->save($thumbnail_path);
```
i don't know how it means, and i tried the fromFilesystem before, also return an undefined error, and i tried different value in fromDisk like `fromDisk(public_path())` or `fromDisk('vidpuz')` also not working

**Comment by pascalbaljet** [comment]
You are using the wrong FFMpeg class, same issue as https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/7.
