### ISSUE TITLE
How to get a frame from video?

### ISSUE THREAD

**Issue by oimken** [pascalbaljetmedia/laravel-ffmpeg#29]
I try to follow the doc to get  a frame from video, but no luck...

I take a look in MediaExporter, I think maybe `function getFormat ` is the cause.

https://github.com/pascalbaljetmedia/laravel-ffmpeg/blob/master/src/MediaExporter.php#L24

Btw:
If I want to save the Frame image at the same folder with video, that will be error:
https://github.com/pascalbaljetmedia/laravel-ffmpeg/blob/master/src/MediaExporter.php#L58

**Comment by pascalbaljet** [comment]
Please post your code and some debugging information, this way your issue is quite unclear to me.

**Comment by oimken** [comment]
At first I just copy your sample code to test it,
but `FFMpeg::fromDisk('videos')` gives me `Non-static method 'fromDisk' should not be called`.
So, here is my code:
```
use Pbmedia\LaravelFFMpeg\FFMpeg;
Class VideosController {
   
    public function __construct(FFMpeg $ffmpeg)
    {
        $ffmpeg->fromDisk('local')
        ->open('video-background.mp4')
        ->getFrameFromSeconds(10)
        ->export()
        ->toDisk('local')
        ->save('video-background.png');
     }
}
```
Error:
```
League \ Flysystem \ FileNotFoundException
File not found at path:
```
ScreenShoot：
![](https://ws1.sinaimg.cn/large/006tKfTcgy1fisc2yqa40j31kw116diw.jpg)

**Comment by pascalbaljet** [comment]
https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/7 https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/18 https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/23 https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/28

**Comment by oimken** [comment]
Still got nothing.  no output and frame not found.
......  
Looking forward for running sample.

**Comment by pascalbaljet** [comment]
Again, I can't help you with such little information.

https://pascalbaljetmedia.com/en/blog/how-to-use-ffmpeg-in-your-laravel-projects
