### ISSUE TITLE
Filter crf without bitrate

### ISSUE THREAD

**Issue by martin-1988** [pascalbaljetmedia/laravel-ffmpeg#30]
Hello

I have a little problem. I can add the '-crf' filter without any problem, but it doesn't have any effect on the quality and size of the videos. I think I must also remove the **'-b:v' '100k'** bitrate filter which is automaticly added when I save the file in the x264 format. I think when I can remove the bitrate filter the crf filter will work as expected.

At the moment is the output is following and I want to remove the **'-b:v' '100k'** completly. How is this possible`?

'/usr/bin/ffmpeg' '-y' '-i' 'bla.mp4' '-preset' 'slow' '-crf' '28' '-threads' '12' '-vcodec' 'libx264' '-acodec' 'libfaac' **'-b:v' '100k'** '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-vf' '[in]scale=1440:-1[out]' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes59a47fa95d453sukeb/pass-59a47fa95da34' '/tmp/laravel-ffmpegVA4Ye7.mp

https://trac.ffmpeg.org/wiki/Encode/H.264

`            $ffmpeg = FFMpeg::open($save_path.$filename)
            ->addFilter(['-vf', 'scale=1440:-1', '-preset', 'slow', '-crf', 28])
            ->export()
            ->toDisk('supercdn')
            ->inFormat((new \FFMpeg\Format\Video\X264)->setKiloBitrate(100))
            ->save("/test/.$filename);`

Thanks a lot for your help!

**Comment by pascalbaljet** [comment]
The underlying package [adds the bitrate command](https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/96225b2dff65a4c3b0b541f2420742ffe5851127/src/FFMpeg/Media/Video.php#L88) when your format is an instance of `VideoInterface`. I think you should try to create a custom format that implements the `FormatInterface` instead, that way you can supply your own set of filters.
