### ISSUE TITLE
process remote url's ?

### ISSUE THREAD

**Issue by MJunaidAhmad** [pascalbaljetmedia/laravel-ffmpeg#31]
I want to confirm that, is there any way around that I can give a remote url to the ffmpeg object and it will then download the file in the specified format. Something like that:
```
FFMpeg::fromDisk('remoteURL')
    ->open('www.someyrl.com/sdfsd/sdsd/sd/ds/yesterday.mp3')
    ->export()
    ->toDisk('converted_songs')
    ->inFormat(new \FFMpeg\Format\Audio\Flac)
    ->save('yesterday.flac');
```
If so then what will be the syntax for that I mean fromDisk or fromFileStorage and what argument to provide this. 
One last question, is .flac format supported?

**Comment by pascalbaljet** [comment]
Flac is supported by the underlying package, just use this format:
https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/master/src/FFMpeg/Format/Audio/Flac.php

I'll check out if FFmpeg itself supports URLs as input, but for now you can store the audio file locally and then open it:

```php
use FFMpeg;
use Illuminate\Support\Facades\Storage;

$remoteUrl = 'https://something.com/audio.mp3';

Storage::disk('your_disk')
    ->put('audio.mp3', file_get_contents($remoteUrl));

FFMpeg::fromDisk('your_disk')
    ->open('audio.mp3')
    ->etc(...);

**Comment by MJunaidAhmad** [comment]
oh, Thanks alot :)

**Comment by tranducit95** [comment]
> Flac is supported by the underlying package, just use this format:
> https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/master/src/FFMpeg/Format/Audio/Flac.php
> 
> I'll check out if FFmpeg itself supports URLs as input, but for now you can store the audio file locally and then open it:
> 
> ```
> use FFMpeg;
> use Illuminate\Support\Facades\Storage;
> 
> $remoteUrl = 'https://something.com/audio.mp3';
> 
> Storage::disk('your_disk')
>     ->put('audio.mp3', file_get_contents($remoteUrl));
> 
> FFMpeg::fromDisk('your_disk')
>     ->open('audio.mp3')
>     ->etc(...);
> ```

Sr, but FFmpeg now support URLs?

**Comment by abbieben07** [comment]
> > Flac is supported by the underlying package, just use this format:
> > https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/master/src/FFMpeg/Format/Audio/Flac.php
> > I'll check out if FFmpeg itself supports URLs as input, but for now you can store the audio file locally and then open it:
> > ```
> > use FFMpeg;
> > use Illuminate\Support\Facades\Storage;
> > 
> > $remoteUrl = 'https://something.com/audio.mp3';
> > 
> > Storage::disk('your_disk')
> >     ->put('audio.mp3', file_get_contents($remoteUrl));
> > 
> > FFMpeg::fromDisk('your_disk')
> >     ->open('audio.mp3')
> >     ->etc(...);
> > ```
> 
> Sr, but FFmpeg now support URLs?

please how do i setup a remote url call
