### ISSUE TITLE
Can't make public the exported video to S3

### ISSUE THREAD

**Issue by enzonotario** [pascalbaljetmedia/laravel-ffmpeg#32]
Hi! I'm using your library and it works fine! But now I'm trying to use it with S3.
When I upload a file to S3 I do:
`\Storage::putFile('videos', $request->file('file'), 'public')`

I mean, I have to declare it as `public` to allow my users to see the video.

If I use your library, I don't know how to declare it as public.

What I do is:
```
FFMpeg::fromDisk('s3')
            ->open($filename)
            ->addFilter($watermarkFilter)
            ->export()
            ->toDisk('s3')
            ->inFormat(new X264('libmp3lame'))
            ->save($savedFilename);
```

Can you help me, please?

**Comment by pascalbaljet** [comment]
I've just released a new version which has a `withVisibility` method on the exporter:

```php
FFMpeg::fromDisk('s3')
    ->open($filename)
    ->addFilter($watermarkFilter)
    ->export()
    ->inFormat(new X264('libmp3lame'))
    ->withVisibility('public')
    ->save($savedFilename);
```

Also, in this case you could discard the `toDisk` method since the input disk is the same as the output disk ;-)
