### ISSUE TITLE
Customfilter single quote

### ISSUE THREAD

**Issue by ojsoft** [pascalbaljetmedia/laravel-ffmpeg#34]
I try to set some Text using a custom filter:

```php
$customFilter = new CustomFilter("drawtext=\"fontfile=/usr/local/fonts/whitrabt.ttf: text='My Text': fontcolor=black: fontsize=24: box=1: boxcolor=white@0.5: boxborderw=5: x=(w-text_w)/2: y=(h-text_h)/2\"");
```

The problematic part is:  text='My Text'

This always converts in the ffmpeg command to text=\\'\\"My Text\\"\\'

Well that is not working of course, I tried with all kinds of tricks to get around this problem, like

text=\\'My Text\\'
text=\\\\'My Text\\\\'
text=\\\\\\'My Text\\\\\\'
a.s.o. wrapped the whole thing different a.s.o.

Well the result is always different but somehow always a additional \\" appear where they shouldn’t.

I bet that you are doing something too clever in your code to clean the filter line before inserting it to the command line, that causes the problem.

In the end it should result in:

text=\\'My Text\\'

inside the ffmpg command line, because the whole $filter is wrapped in ' already. Do you have a hint for me, or do you think you can fix that?

**Comment by pascalbaljet** [comment]
It seems this is a known issue with FFmpeg:
https://stackoverflow.com/questions/10725225/ffmpeg-single-quote-in-drawtext

**Comment by pascalbaljet** [comment]
Any updates on this issue?

**Comment by ojsoft** [comment]
Well, it still does not work… i just skipped this issue so far, due to my current work load.
I still did not find time to make a small example. Please excuse… I am pretty sure though if you just try to add some custom text yourself on any video, you will face the same problems.

With best regards,

Oliver
