### ISSUE TITLE
MPEG-DASH support ?

### ISSUE THREAD

**Issue by codegeek1001** [pascalbaljetmedia/laravel-ffmpeg#36]
Wondering if there is any plans to add support for MPEG-DASH ?

**Comment by pascalbaljet** [comment]
There is only support for HLS for now but you could probably do it with some custom filters and these posts:

- https://blog.streamroot.io/encode-multi-bitrate-videos-mpeg-dash-mse-based-media-players/
- https://tdngan.wordpress.com/2016/11/17/how-to-encode-multi-bitrate-videos-in-mpeg-dash-for-mse-based-media-players/
