### ISSUE TITLE
Merge two audio files

### ISSUE THREAD

**Issue by noconcept** [pascalbaljetmedia/laravel-ffmpeg#37]
Hey, first of all thanks for a great package.

I'm trying to merge two audio files together using the amix filter. I've got the command line working so I'm simply trying to get it working using your package.

This is what I'm trying:
```
FFMpeg::fromDisk('s3')
        ->open($this->path) // equals main.wav
        ->open('/songs/tag.wav')
        ->addFilter('-filter_complex amix=inputs=2:duration=first:dropout_transition=3');
        ->export()
        ->inFormat(new \FFMpeg\Format\Audio\Mp3)
        ->save('/songs/main/' . $this->id . '.mp3', 'public');
    }
```

And this is the working command line
```
ffmpeg -i main.wav -i tag.wav -filter_complex amix=inputs=2:duration=first:dropout_transition=3 main.mp3
```

If you can help me with this, or provide any references to similar code it would be greatly appreciate.

Thanks again!

**Comment by noconcept** [comment]
I believe I got this working correctly!

Here's my code if anyone runs into this problem:

```
$media = FFMpeg::fromDisk('s3')
                    ->open($this->path);

    $media->addFilter(new SimpleFilter([
            '-i', 'link to audio tag', '-filter_complex','amix=inputs=2:duration=first:dropout_transition=3'
          ]))
          ->export()
          ->inFormat(new \FFMpeg\Format\Audio\Mp3)
          ->save('/songs/main/' . $this->id . '.mp3', 'public');
    }
```

**Comment by mohammedobaid1234** [comment]
Hey, first of all thanks for a great package.

how can make this command
ffmpeg -f concat -i 2.txt -c copy Two_BeSureToWearFlowersInYourHair.wav
by laravel

**Comment by developer-macrew** [comment]
Hi @noconcept 

I have same thing, I want to repeat background audio till the voice audio length, but I'm not able to add stream_loop filter here.

Thanks

**Comment by jgodstime** [comment]
> I believe I got this working correctly!
> 
> Here's my code if anyone runs into this problem:
> 
> ```
> $media = FFMpeg::fromDisk('s3')
>                     ->open($this->path);
> 
>     $media->addFilter(new SimpleFilter([
>             '-i', 'link to audio tag', '-filter_complex','amix=inputs=2:duration=first:dropout_transition=3'
>           ]))
>           ->export()
>           ->inFormat(new \FFMpeg\Format\Audio\Mp3)
>           ->save('/songs/main/' . $this->id . '.mp3', 'public');
>     }
> ```

@developer-macrew , please how do I get the new merged file URL using the snippet, Somethings  like $media->getFileUlr()
