### ISSUE TITLE
FFProbe

### ISSUE THREAD

**Issue by matrunchyk** [pascalbaljetmedia/laravel-ffmpeg#4]
Hi guys,

Sorry I'm writing this question to Issues section, but do you have any plans to support [FFProbe](https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/master/src/FFMpeg/FFProbe.php)?

How do you fetch information of a media?

Thank you.

**Comment by pascalbaljet** [comment]
The Media object you get when you 'open' a file, actually holds the Media object that belongs to the [underlying driver](https://github.com/PHP-FFMpeg/PHP-FFMpeg). It handles dynamic method calls as you can see [here](https://github.com/pascalbaljetmedia/laravel-ffmpeg/blob/master/src/Media.php#L104-L109). This way all methods of the underlying driver are still available to you.

```php
// This gives you an instance of Pbmedia\LaravelFFMpeg\Media
$media = FFMpeg::fromDisk('videos')->open('video.mp4');

// The 'getStreams' method will be called on the underlying Media object since 
// it doesn't exists on this object.
$codec = $media->getStreams()->first()->get('codec_name');
```

If you want direct access to the underlying object, call the object as a function (invoke):

```php
// This gives you an instance of Pbmedia\LaravelFFMpeg\Media
$media = FFMpeg::fromDisk('videos')->open('video.mp4');

// This gives you an instance of FFMpeg\Media\MediaTypeInterface
$baseMedia = $media();
```

**Comment by matrunchyk** [comment]
Wow, that's really flexible. 
Maybe it would be cool to mention it in **README.md**.

Thank you for the fast response!

**Comment by pascalbaljet** [comment]
No problem, thanks for using it! I'll add it to the documentation in the next release 👍
