### ISSUE TITLE
does it support images to video ? 

### ISSUE THREAD

**Issue by badrsh** [pascalbaljetmedia/laravel-ffmpeg#40]
Hi , 
does this package  support images to video  ?

**Comment by pascalbaljet** [comment]
Could you give an example? I guess you want to create a video out of a series of images?

**Comment by badrsh** [comment]
Yes that what I'm looking for

**Comment by pascalbaljet** [comment]
It's not supported out of the box but you can probably do it with some custom filters. I haven't tested this one but I think you need something like this:

```php
FFMpeg::fromDisk('images')
    ->open('image%04d.jpg')
    ->addFilter('-r', 60)
    ->addFilter('-f', 'image2')
    ->export()
    ->toDisk('videos')
    ->inFormat(new \FFMpeg\Format\Video\X264)
    ->save('video.mp4');
```

Here are two resources to read more about it:
http://hamelot.io/visualization/using-ffmpeg-to-convert-a-set-of-images-into-a-video/
https://en.wikibooks.org/wiki/FFMPEG_An_Intermediate_Guide/image_sequence
