### ISSUE TITLE
Unable to save concatenated video

### ISSUE THREAD

**Issue by HeroSony** [pascalbaljetmedia/laravel-ffmpeg#42]
I've tried to merge videos and followed this part https://github.com/PHP-FFMpeg/PHP-FFMpeg#concatenation and this is my code:

(1)
```
$ffmpeg = FFMpeg::fromDisk('public');
$video = $ffmpeg->open('/downloadable_videos/clip1.mp4' );
$mergeFile = $video->concat(array('downloadable_videos/clip1.mp4', '/downloadable_videos/clip2.mp4'))
		    			->saveFromSameCodecs('/downloadable_videos/output.mp4', TRUE);
```

Finnally, I've got this error.
![image](https://user-images.githubusercontent.com/4160246/32531109-a4354e88-c474-11e7-80cb-50ae99fd51b4.png)

(2)
Anyway, I try to make my own way: 
Create concat.txt and put contents:
file 'clip1.mp4'
file 'clip2.mp4'

and run this command:
`$  ffmpeg.exe -f concat -i concat.txt -c copy -an output.mp4`
it's working fine, but you know how can i implement this into code?

Do you have any examples(1) or show me some tips on how to implement(2)?

**Comment by pascalbaljet** [comment]
It's probably cause your paths are wrong. I haven't tested it myself but could you try this:

```php
$disk = FFMpeg::fromDisk('public');

$video1 = $disk->open('/downloadable_videos/clip1.mp4');
$video2 = $disk->open('/downloadable_videos/clip2.mp4');
$output = $disk->open('/downloadable_videos/output.mp4');

$video1->concat([
    $video1->getPathfile(),
    $video2->getPathfile(),
])->saveFromSameCodecs($output->getFullPath(), true);
```

**Comment by HeroSony** [comment]
@pascalbaljet, I'll try yours. Thank!

**Comment by daviidy** [comment]
@pascalbaljet i've tried your solution, but i get this error: Unable to probe C:\Users\DELL\Documents\workspace\repetbox\storage\app/public\out-1589542760.mp4
