### ISSUE TITLE
Duration time of clipped video

### ISSUE THREAD

**Issue by rvsky** [pascalbaljetmedia/laravel-ffmpeg#45]
Hi! I see that I can clip video here:
$start = \FFMpeg\Coordinate\TimeCode::fromSeconds(5)
$clipFilter = new \FFMpeg\Filters\Video\ClipFilter($start);

So, I can start video from 5second, but where to change duration time?
For example I have 15 min video and how to make 15 sec from it starting from one minute?

**Comment by pascalbaljet** [comment]
Take a look at the source of ```ClipFilter```, you can pass in the duration as a second parameter.

https://github.com/PHP-FFMpeg/PHP-FFMpeg#clip
