### ISSUE TITLE
Unable to load FFProbe

### ISSUE THREAD

**Issue by rvsky** [pascalbaljetmedia/laravel-ffmpeg#46]
As above. I am using ubuntu 16.04 and 

    	$ffmpeg = \FFMpeg\FFMpeg::create();

**Comment by pascalbaljet** [comment]
Try to do a bit more debugging and investigation before opening issues. Read the documentation, scan the source code, follow the example app, etc.

When you open an issue, please attach some meaningful information. There is no way I can help you without some code, debugging info and error logs.
