### ISSUE TITLE
HLS and MediaExporter merge to official PHP-FFMpeg?

### ISSUE THREAD

**Issue by adriangoris** [pascalbaljetmedia/laravel-ffmpeg#47]
Would it be beneficial to merge the HLS and MediaExporter feature to the official PHP-FFMpeg? 

HLS is pretty much a standard for streaming online video. 

I ended up having to fork the original project to add HLS support and many others use setAdditionalParameters feature to achieve the same goal.  

After going through your repo,  I realized @pascalbaljet is much further along than me in implementing the full FFmpeg HLS feature set.

@jens1o

**Comment by pascalbaljet** [comment]
It's probably better to open an issue or PR on the PHP-FFMpeg repository. My implementation is very optionated and probably needs a rewrite before it can be merged into the PHP-FFMpeg repo.

**Comment by jens1o** [comment]
I would also like to have that feature in the core package, will definitely support the progress :)
