### ISSUE TITLE
Laravel not clipping my video

### ISSUE THREAD

**Issue by rvsky** [pascalbaljetmedia/laravel-ffmpeg#48]
Hi! I am trying to clip video. Log says that everything is successful, i got blank screen but my video had 9 seconds and it had again 9 seconds.
here's code: 

```
FFMpeg::fromDisk('public')
    ->open('/uploads/videos/' .$video->file_name)
    ->filters()
    ->clip(FFMpeg\Coordinate\TimeCode::fromSeconds(2), FFMpeg\Coordinate\TimeCode::fromSeconds(2))
    ->synchronize();
```

What should I do?

**Comment by pascalbaljet** [comment]
Please read the documentation about exporting and using filters:
https://github.com/pascalbaljetmedia/laravel-ffmpeg#usage

**Comment by rvsky** [comment]
@pascalbaljet what do u mean?
