### ISSUE TITLE
Transcoding Progressbar Implementation?

### ISSUE THREAD

**Issue by COLABORATI** [pascalbaljetmedia/laravel-ffmpeg#49]
Thank you very much for this very nice package, it is really a great example of Laravel usage!

Q: What would be your recommendation for implementing a progressbar for the transcoding? Do exist any similar Laravel packages / examples that show how to do this in a "Laravel way"?

Thanks for your attention!

**Comment by pascalbaljet** [comment]
You can add a listener to the format and then broadcast an Event (with Laravel). The format classes implement the ```FFMpeg\Format\ProgressableInterface``` interface. First make the event with the Artisan CLI and make sure the event implements the ```ShouldBroadcast``` interface.

```bash
php artisan make:event TranscodingProgressUpdated
```

Then dispatch an event in the progress listener:

```php
$format = new \FFMpeg\Format\Video\X264;
$format->on('progress', function($video, $format, $percentage) {
    event(new TranscodingProgressUpdated($percentage));
});

FFMpeg::open('my_movie.mov')
    ->export()
    ->inFormat($format)
    ->save('my_movie.mkv');
```

With [Laravel Echo](https://laravel.com/docs/5.5/broadcasting#installing-laravel-echo) you can listen for events in your Javascript code.

This is how I do it and it works great! Please read the documentation about events, broadcasting and the ProgressableInterface carefully:

https://laravel.com/docs/5.5/broadcasting
https://laravel.com/docs/5.5/events
https://github.com/PHP-FFMpeg/PHP-FFMpeg#formats
