### ISSUE TITLE
FrameFilterInterface expected instead of SegmentedFilter

### ISSUE THREAD

**Issue by ojsoft** [pascalbaljetmedia/laravel-ffmpeg#5]
Hello,

I am already on Laravel 5.4. Maybe it is an incompatibility issue with the newest version. Have a look at the stack trace.

With best regards,

Oliver

Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to FFMpeg\Media\Frame::addFilter() must be an instance of FFMpeg\Filters\Frame\FrameFilterInterface, instance of Pbmedia\LaravelFFMpeg\SegmentedFilter given in /Users/oj/code/kinklink/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/Frame.php:61
Stack trace:
#0 [internal function]: FFMpeg\Media\Frame->addFilter(Object(Pbmedia\LaravelFFMpeg\SegmentedFilter))
#1 /Users/oj/code/kinklink/vendor/pbmedia/laravel-ffmpeg/src/Media.php(77): call_user_func_array(Array, Array)
#2 /Users/oj/code/kinklink/vendor/pbmedia/laravel-ffmpeg/src/SegmentedExporter.php(46): Pbmedia\LaravelFFMpeg\Media->addFilter(Object(Pbmedia\LaravelFFMpeg\SegmentedFilter))
#3 /Users/oj/code/kinklink/vendor/pbmedia/laravel-ffmpeg/src/HLSPlaylistExporter.php(74): Pbmedia\LaravelFFMpeg\SegmentedExporter->saveStream('/Users/oj/code/...')
#4 /Users/oj/code/kinklink/vendor/pbmedia/laravel-ffmpeg/src/HLSPlaylistExporter.php(95): Pbmedia\LaravelFFMpeg\HLSPlaylistExporter->exportStreams()
#5 /Users/oj/code/kinklink/vendor/pbmedia/laravel-ffmpeg/src/MediaExporter.php(60): Pbmedia\LaravelFFMpeg\HLSPlaylistExporter->savePlaylist('/Users/oj/code/...')
#6 /Users/oj/code/kinklink/app/Jobs/ProcessContentVideo.php(118): Pbmedia\LaravelFFMpeg\MediaExporter->save('/Users/oj/code/...')
#7 [internal function]: App\Jobs\ProcessContentVideo->handle()

**Comment by marco-aa** [comment]
Maybe it's related to :
https://secure.php.net/manual/de/migration71.incompatible.php
PHP 7.0 only is written in laravel-ffmpeg description

**Comment by ojsoft** [comment]
> Am 01.02.2017 um 03:42 schrieb marco-aa <notifications@github.com>:
> 
> Maybe it's related to :
> https://secure.php.net/manual/de/migration71.incompatible.php <https://secure.php.net/manual/de/migration71.incompatible.php>
> PHP 7.0 only is written in laravel-ffmpeg description
> 
Das habe ich auch gelesen, aber an anderer Stelle steht auch ^7.0 das bedeutet grösser als… als er das geschrieben hat gab es ggf noch kein 7.1

**Comment by ojsoft** [comment]
I found the problem, it was my mistake. To export to an image and then export to a video in a ow is no good idea. I contatenated that to save another open statement.
Sorry!

**Comment by pascalbaljet** [comment]
Glad you found the error. This package should be compatible with PHP 7.1 too:
https://travis-ci.org/pascalbaljetmedia/laravel-ffmpeg/builds/197229264

**Comment by ojsoft** [comment]
Hello Pascal,

you are really quick in reacting on Issues it looks like. Thank you for the work you have done, it is really helpful.

I am sorry for filing this issue to soon…. This time though I really tried hard to eliminate possible mistakes on my side
or lets say, I have no idea how to get around, without patching your code:

[2017-02-02 12:47:39] local.INFO: ffmpeg running command '/usr/local/bin/ffmpeg' '-y' '-i' '/Users/oj/code/kinklink/storage/app/public/users/1/upload/p3Anee5RoWmd-1.mp4' '-map' '0' '-flags' '-global_header' '-f' 'segment' '-segment_format' 'mpeg_ts' '-segment_list' '/Users/oj/code/kinklink/storage/app/public/users/1/content/p3Anee5RoWmd-1_250.m3u8' '-segment_time' '10' '-threads' '12' '-vcodec' 'libx264' '-acodec' 'libmp3lame' '-b:v' '250k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-pass' '1' '-passlogfile' '/var/folders/g_/b9xjq9yx6859bxwchm6tqp0c0000gr/T/ffmpeg-passes58932a6b4a6acfitu5/pass-58932a6b4a77e' '/Users/oj/code/kinklink/storage/app/public/users/1/content/p3Anee5RoWmd-1_250_%05d.ts'  
[2017-02-02 12:47:40] local.ERROR: ErrorException: A non-numeric value encountered in /Users/oj/code/kinklink/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Format/ProgressListener/AbstractProgressListener.php:182
Stack trace:
#0 /Users/oj/code/kinklink/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Format/ProgressListener/AbstractProgressListener.php(182): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'A non-numeric v...', '/Users/oj/code/...', 182, Array)
#1 /Users/oj/code/kinklink/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Format/ProgressListener/AbstractProgressListener.php(136): FFMpeg\Format\ProgressListener\AbstractProgressListener->parseProgress('frame=  659 fps...')
#2 /Users/oj/code/kinklink/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(90): FFMpeg\Format\ProgressListener\AbstractProgressListener->handle('err', 'frame=  659 fps...')
#3 [internal function]: Alchemy\BinaryDriver\ProcessRunner->Alchemy\BinaryDriver\{closure}('err', 'frame=  659 fps...')
#4 /Users/oj/code/kinklink/vendor/symfony/process/Process.php(1345): call_user_func(Object(Closure), 'err', 'frame=  659 fps...')
#5 /Users/oj/code/kinklink/vendor/symfony/process/Process.php(1450): Symfony\Component\Process\Process->Symfony\Component\Process\{closure}('err', 'frame=  659 fps...')

There is a crash that has to do with the AbstractProgressListener.php

My work around currently is to comment out a 3 lines in Media/Video.php,
because I have no need for any progress.

// if ($format instanceof ProgressableInterface) {
//     $listeners = $format->createProgressListener($this, $this->ffprobe, $pass + 1, $totalPasses);
// }
Then it works all fine.

It would be cool though if I can switch progress of in your Bundle like:

->export()->noprogress()
to get around this problem,of course I could make my own wrapper class to fix it too, but something alike that would be more handy.
Or maybe you just have a look why the error happens, I guess it has to do with some unexpected result in the ffmpeg output that is parsed during progress.
With best regards,

Oliver Jörns

**Comment by pascalbaljet** [comment]
These three lines of code are part of the underlying php-ffmpeg package, not this package. Could you open a new issue with some code so I can reproduce your issue? Thanks!
