### ISSUE TITLE
Realtime HLS Encoding Progress Percentage

### ISSUE THREAD

**Issue by alexykouakou** [pascalbaljetmedia/laravel-ffmpeg#51]
I use VueJs to Upload a video and sent it to a Job,
My Job code looks like:
```
    public function handle()
    {
        $file = public_path().'/storage/user_uploads/media/cache/'. $this->filename;

        $lowBitrate = (new X264())->setKiloBitrate(50)->setAudioCodec('aac');
        $midBitrate = (new X264)->setKiloBitrate(150)->setAudioCodec('aac');
        $highBitrate = (new X264)->setKiloBitrate(300)->setAudioCodec('aac');

        FFMpeg::fromDisk('videos-cache')
            ->open($this->filename)
            ->exportForHLS()
            ->onProgress(function ($percentage) {
                event(new EncodingProgressUpdated($percentage)); // method 1
                $this->media->processed_percentage = $percentage; // method 2
                $this->media->save();
            })
            ->setSegmentLength(1)
            ->addFormat($lowBitrate, function($media) {
                    $media->addFilter(function ($filters) {
                        $filters->resize(new \FFMpeg\Coordinate\Dimension(416, 234));
                    });
                })
            ->toDisk('medias')
            ->save($this->uid.'/'.$this->uid.'.m3u8');

        $this->media->media_filename = $this->uid.'.m3u8';
        $this->media->save();
    }
```

onProgress function doesnt sent event and with method 2, $percentage is not sent to my database. I cant retrive also $percentage outside the function. This code inside the function: global $percentage doesnt pass $percentage value outside.

How can I retrieve $percentage, send it to an event or to my database ?

**Comment by pascalbaljet** [comment]
What happens when you log the percentage?

```php
->onProgress(function ($percentage) {
    \Log::info('HLS export', compact('percentage'));
})

**Comment by alexykouakou** [comment]
HLS percentage is exported to Log like this:
`[2017-11-30 07:51:15] local.INFO: HLS export {"percentage":48} `

**Comment by pascalbaljet** [comment]
That means the callback method is working! 

Maybe the ‘processed_percentage’ attribute in your Model is still guarded? Regarding your event, if it’s being processed by the same (single) queue worker as the Job, it doesn’t get processed until the Job is finished. Try to set up another queue just for the FFmpeg jobs.

**Comment by pascalbaljet** [comment]
Any updates on this issue?

**Comment by Adamkaram** [comment]
how i can log my percentage in this code 

  public function handle()
    {
      $low = (new X264('aac'))->setKiloBitrate(100);
      $med = (new X264('aac'))->setKiloBitrate(250);
      $high = (new X264('aac'))->setKiloBitrate(500);

      FFMpeg::fromDisk('local')
      ->open($this->video->path)
      ->exportForHLS()
      ->onProgress(function ($percentage) {
                $this->video->update([
                    'percentage' => $percentage,
                    Log::info('HLS export', compact('percentage'))
                ]);
            })


      ->addFormat( $low)
      ->addFormat($med)
      ->addFormat($high)
      ->save("public/videos/{$this->video->id}/{$this->video->id}.m3u8");
}
}
