### ISSUE TITLE
How to just get dimensions from the video

### ISSUE THREAD

**Issue by vedmant** [pascalbaljetmedia/laravel-ffmpeg#54]
Hi, I can't find how I just can get dimensions from the video, I need width and height.

**Comment by pascalbaljet** [comment]
This is how get a `FFMpeg\Coordinate\Dimension` object:

```php
FFMpeg::open('video.mp4')
    ->getStreams()
    ->videos()
    ->first()
    ->getDimensions();
```

**Comment by boz14676** [comment]
Thanks 👍

**Comment by michaelaguiar** [comment]
For videos with the height > width, it's giving me the height for the width value?  Any issues with this?
