### ISSUE TITLE
How to convert audio to video ?

### ISSUE THREAD

**Issue by huynhphan89** [pascalbaljetmedia/laravel-ffmpeg#55]
I often run this command line to convert audio to video for uploading  to YouTube. 

`ffmpeg -v quiet -loop 1 -r 1 -i "cover.jpg" -i "audio.mp3" -c:a copy -shortest "video.avi"`

How to do that with your library ?
Many thanks.

**Comment by pascalbaljet** [comment]
Open the Audio file and apply a custom filter to add the image on top. It’s all in the README.md.
