### ISSUE TITLE
Support for x265 codec?

### ISSUE THREAD

**Issue by jeffsfotofix** [pascalbaljetmedia/laravel-ffmpeg#56]
So far this has been easy to install and use, although I am curious - am I able to use the x265 codec?

**Comment by pascalbaljet** [comment]
You should extend the `DefaultVideo` class of the underlying driver:
https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/master/src/FFMpeg/Format/Video/DefaultVideo.php

That way you can specify all the details, just like the class`X264`:
https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/master/src/FFMpeg/Format/Video/X264.php

**Comment by pascalbaljet** [comment]
Also make sure you use a FFmpeg build with H.265 support:
https://trac.ffmpeg.org/wiki/Encode/H.265

**Comment by francoism90** [comment]
@pascalbaljet Could you give a little more details? :)
I want to add HWAccel as a preset, where exactly should you place the 'extend'?

Thanks!
