### ISSUE TITLE
Unable to Probe video

### ISSUE THREAD

**Issue by nfunwigabga** [pascalbaljetmedia/laravel-ffmpeg#57]
Each time I try to encode, I get a Runtime error message `unable to probe <video path>`.  This for instance gives that error:
```php
$lowBitrateFormat  = (new X264('libmp3lame', 'libx264'))->setKiloBitrate(500);
$midBitrateFormat  = (new X264('libmp3lame', 'libx264'))->setKiloBitrate(1500);
$highBitrateFormat = (new X264('libmp3lame', 'libx264'))->setKiloBitrate(3000);
        
FFMpeg::fromDisk('server')
    ->open('videos/'.$this->filename)
    ->exportForHLS()
    ->toDisk('streamable_videos')
    ->addFormat($lowBitrateFormat)
    ->addFormat($midBitrateFormat)
    ->addFormat($highBitrateFormat)
    ->save('test.m3u8');
```
Any idea why? I even changed the folder permissions to 777 just in case, but still have the same problem. I'm using version ^1.3.

**Comment by codiiv** [comment]
@pascalbaljet Any idea why this is not working?

**Comment by pascalbaljet** [comment]
I think the video path is wrong.

**Comment by codiiv** [comment]
You are right. I found out I was using app_path() I had defined customly instead of storage_path(). I works now and I like it ☺
