### ISSUE TITLE
fromDesk is not static function, is it supposed to be called non-statically? 

### ISSUE THREAD

**Issue by Abu3safeer** [pascalbaljetmedia/laravel-ffmpeg#62]
Hello,
I am using PHPStorm, I noticed that it only shows me getFilesystems & newTemporaryFile methods only, I thought I am using the wrong class, but when I explored FFMpeg file, I noticed that most all functions except the mentioned before are not static, so they should be called with the object.

If I try to create an object, it requires three parameters.
I have checked this:
https://pascalbaljetmedia.com/en/blog/how-to-use-ffmpeg-in-your-laravel-projects

```
// open the uploaded video from the right disk...
        FFMpeg::fromDisk($this->video->disk)
            ->open($this->video->path)
```

is that outdated code, or I misunderstood something.

**Comment by pascalbaljet** [comment]
Read the Laravel documentation about Facades, this has been asked multiple times already:

https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/7
https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/18

**Comment by Abu3safeer** [comment]
I see, sorry for that, I forgot about it.

**Comment by carrotis** [comment]
Please show me sample code.

**Comment by Abu3safeer** [comment]
Do you use an IDE?

**Comment by carrotis** [comment]
Nope, I need full sample code working

2018년 3월 24일 (토) 오후 8:39, Abu3safeer <notifications@github.com>님이 작성:

**Comment by Abu3safeer** [comment]
All simples are here:
https://github.com/pascalbaljetmedia/laravel-ffmpeg
