### ISSUE TITLE
php-FFMpeg detects ffmpeg from system path, but this have predefined settings. "Executable not found"

### ISSUE THREAD

**Issue by Abu3safeer** [pascalbaljetmedia/laravel-ffmpeg#63]
Hello,
I noticed that settings are located in 'config\laravel-ffmpeg.php'.
but the original php-ffmpeg detect ffmpeg from system PATH.

> "Executable not found, proposed : /usr/local/bin/ffprobe"

**Comment by Abu3safeer** [comment]
I know where ffmpeg is, but I already added it to system path, so it needs to detect where to find it on vary systems.

**Comment by pascalbaljet** [comment]
It doesn’t need to detect anything, you just have to adjust the config file. Please read the documentation before opening issues.

**Comment by Abu3safeer** [comment]
in https://github.com/PHP-FFMpeg/PHP-FFMpeg you just invoke FFMpeg\FFMpeg::create(); without any configurations, it searches for ffmpeg in PATH virble, but this uses the configuration.

**Comment by pascalbaljet** [comment]
What’s the problem? If you know where the binaries are located, add them the config file and off you go. I don’t like the idea of binary detection, the config file with optional environment handling is much more reliable imho.

**Comment by Abu3safeer** [comment]
the problem is ffmpeg installed in different locations, depending on the environment, in UNIX based system it may vary, especially if it is installed from repository manager, on the other hand windows does not have PATH, so you could benefit from selecting the direction.

but as you know most hosts use linux systems, so using PATH is useful in this case.

Regards.
