### ISSUE TITLE
Update for Laravel 5.6

### ISSUE THREAD

**Issue by francoism90** [pascalbaljetmedia/laravel-ffmpeg#65]
Thanks!

**Comment by sullyfischer** [comment]
+1

**Comment by uschmann** [comment]
I think the problem is related to 
php-ffmpeg.

**Comment by liucf** [comment]
@pascalbaljet why it  not working for Laravel 5.6?  will it work in the future?

**Comment by pascalbaljet** [comment]
Version 2.0.0 has been released with Support for Laravel 5.6!
