### ISSUE TITLE
Non-static method Pbmedia\LaravelFFMpeg\FFMpeg::fromDisk() should not be called statically

### ISSUE THREAD

**Issue by sullyfischer** [pascalbaljetmedia/laravel-ffmpeg#7]
Hi there, thank you for creating this package. 
I've just installed it on a Laravel 5.4, and this is the error I get:
`Non-static method Pbmedia\LaravelFFMpeg\FFMpeg::fromDisk() should not be called statically`

this is my code:

```
use Illuminate\Support\Facades\Storage;

public function upload()
    {
        $file = request()->file('gif');
        $name = time() . '.gif';

        $file->storeAs('gifs', $name);

        FFMpeg::fromDisk('local')
                    ->open('gifs/' . $name)
                    ->export()
                    ->inFormat(new \FFMpeg\Format\Video\X264)
                    ->save('export-x264.mp4');

        return back();
    }
```

**Comment by sullyfischer** [comment]
never mind, found it. Should have used it as:
```use Pbmedia\LaravelFFMpeg\FFMpegFacade as FFMpeg;```

Could be nice if you could mention this in the docs. Thanks again

**Comment by pascalbaljet** [comment]
The use of facades is described really well in the [Laravel Documentation](https://laravel.com/docs/5.4/facades) :)
