### ISSUE TITLE
How to use `setPlaylistPath` ?

### ISSUE THREAD

**Issue by amirmasoud** [pascalbaljetmedia/laravel-ffmpeg#72]
Thanks for great repository, How can I use `setPlaylistPath` method, I'm trying to prepend a default path before m3u8 file playlist.
Thanks,

**Comment by pascalbaljet** [comment]
Can't you do something like this?

```php
FFMpeg::fromDisk('videos')
    ->open('your_video.mp4')
    ->exportForHLS()
    ->addFormat($someFormat)
    ->save('subfolder/adaptive_video.m3u8');
```

**Comment by amirmasoud** [comment]
The final m3u8 file is address to `adaptive_video.m3u8` files rather than relative download path. I'm calling the `adaptive_video.m3u8` from another address and it cannot find the `ts` files.
when I add relative path as prefix to m3u8 files, the problem is fixed.

Example working file:

```
#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=250000
download?file=/public/hello/720P_ (2)_mp4/online_250.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=500000
download?file=/public/hello/720P_ (2)_mp4/online_500.m3u8
```

**Comment by pascalbaljet** [comment]
I understand the problem but it's out of the scope of this project. Maybe you should parse and adjust the generated playlist file or generate your own one?
