### ISSUE TITLE
Unable to load FFProbe

### ISSUE THREAD

**Issue by aghidayat** [pascalbaljetmedia/laravel-ffmpeg#73]
i have problem with error 'Unable to load FFProbe', what should i do?

**Comment by pascalbaljet** [comment]
You need to adjust the (published) config file:
https://github.com/pascalbaljetmedia/laravel-ffmpeg/blob/master/config/laravel-ffmpeg.php

**Comment by hzburki** [comment]
@pascalbaljet this url shows a 404
