### ISSUE TITLE
Is it possible to add watermark ?

### ISSUE THREAD

**Issue by AliN11** [pascalbaljetmedia/laravel-ffmpeg#75]
Hi. Is it possible add a watermark photo to video ?

**Comment by pascalbaljet** [comment]
Use the built-in [watermark](https://github.com/PHP-FFMpeg/PHP-FFMpeg#watermark) filter, you should do something like this:

```php
FFMpeg::open('your_video.mp4')
    ->addFilter(function ($filters) {
        $filters->watermark($watermarkPath, [
            'position' => 'relative',
            'bottom' => 50,
            'right' => 50,
        ]);
    })...
```

**Comment by MarcVertigo** [comment]
Can you give an example of the $filters? They don't have it on their docs in the section you linked. Thanks.

**Comment by aliasgarvanak** [comment]
How you can define the watermark path ?
