### ISSUE TITLE
How to remove audio from video

### ISSUE THREAD

**Issue by kodfire** [pascalbaljetmedia/laravel-ffmpeg#77]
How can I remove audio from video? My code is:

FFMpeg::fromDisk('local')
->open($filePath.$fileName)
->export()
->toDisk('local')
->mute()
->inFormat(new \FFMpeg\Format\Video\X264('libmp3lame', 'libx264'))
->save($converted);

**Comment by pascalbaljet** [comment]
Why do you think the mute method would work?

**Comment by kodfire** [comment]
Why shouldn't it?! There is a modification here in:
https://github.com/PHP-FFMpeg/PHP-FFMpeg/pull/366/commits/fb533ba82171e196a1547d75ce4b524e4a18034e

but after adding that no result :( it says method not found!

**Comment by pascalbaljet** [comment]
You should call that method on the VideoFilters object:

```
FFMpeg::fromDisk('local')
    ->open($filePath.$fileName)
    ->addFilter(function ($filters) {
        $filters->mute();
    })
    ->export()
    ->toDisk('local')
    ->inFormat(new \FFMpeg\Format\Video\X264('libmp3lame', 'libx264'))
    ->save($converted);
```

**Comment by patricksebastien** [comment]
Searching all the code for mute = 0 result. Trying to use the Filter ->mute() = `"message": "Call to undefined method FFMpeg\\Filters\\Video\\VideoFilters::mute()",`

I need to create a muted video so that it can autoplay when loaded on a page. Is it possible to simply pass flags to ffmpeg (-an)?

**Comment by pascalbaljet** [comment]
The `mute()` filter was never merged into the underlying library. You can do it manually:

```php
FFMpeg::open('bg.mp4')
    ->export()
    ->addFilter('-an');
```

Unrelated to this package, but I think you can autoplay videos by adding a `muted`attribute  to the `video` element in HTML:

```html
<video muted autoplay loop playsinline>
  <source src="bg.mp4" type="video/mp4">
</video>
```
