### ISSUE TITLE
RTSP Streaming record

### ISSUE THREAD

**Issue by fendiseptiawan0709** [pascalbaljetmedia/laravel-ffmpeg#8]
Is this package support for recording RTSP stream?
E.g. I have url for access my livestream IP Camera, `rtsp://admin:password@192.168.10.12:554/live1.sdp`
How do I record using that URL?

**Comment by pascalbaljet** [comment]
RTSP is not supported by this package but it is possible with the [underlying driver](https://github.com/PHP-FFMpeg/PHP-FFMpeg). You'd probably need to pass in a custom command (something like ```ffmpeg -i rtsp://yoururl.com -o output.mp4```)
