### ISSUE TITLE
FFProbe error and config

### ISSUE THREAD

**Issue by jerauf** [pascalbaljetmedia/laravel-ffmpeg#82]
I'm trying to retrieve a frame of a video. I'm using this code in my controller.

`use Pbmedia\LaravelFFMpeg\FFMpegFacade as FFMpeg;
`
And then to get the frame:

`
	    $media = FFMpeg::open('http://myvideo.com/video/100');
		$frame = $media->getFrameFromString('00:00:13.37');

`

And my error is:

`Unable to load FFProbe`

I looked through the issues here and the config was mentioned but I'm not sure what the paths mean. Shouldn't they be pointing to the vendor folder?

`    'ffmpeg.binaries' => '/usr/local/bin/ffmpeg',
    'ffprobe.binaries' => '/usr/local/bin/ffprobe',
`

**Comment by pascalbaljet** [comment]
They should point to your ffmpeg binaries. You could try finding them by using the ‘which’ command.

**Comment by leen19971** [comment]
I have a similar issue this is my code 
$media = FFMpeg::openUrl('http://localhost/videos/myvideo.mp4')

            ->getFrameFromSeconds(3)
            ->export()
            ->toDisk('public')
            ->save("thumbnails/thumb_{$date}_{$time}.png");

the error is 
Unable to probe http://localhost/videos/myvideo.mp4 

the link is correct the video plays perfectly when i insert http://localhost/videos/myvideo.mp4  in my browser
