### ISSUE TITLE
php-ffmpeg/binary-driver can't be located

### ISSUE THREAD

**Issue by JapSeyz** [pascalbaljetmedia/laravel-ffmpeg#83]
pbmedia/laravel-ffmpeg 2.1.0 requires php-ffmpeg/binary-driver dev-master -> no matching package found

I can't find the repo anywhere either.

**Comment by cryptixcoder** [comment]
I'm having the same issue.

**Comment by pascalbaljet** [comment]
Fixed in 2.1.1, sorry for the hiccup!
