### ISSUE TITLE
export image to disk?

### ISSUE THREAD

**Issue by haideritx** [pascalbaljetmedia/laravel-ffmpeg#84]
`local.ERROR: Call to undefined method FFMpeg\Media\Frame::export() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method FFMpeg\\Media\\Frame::export() at D:\\wamp\\www\\Bankrolla\\app\\Jobs\\ConvertVideoForStreaming.php:62)`

Im trying to save file to defined disk. for local development it stores in local, but for live it stores to s3
but it is not accepting the disk.

```
$media = FFMpeg::fromDisk('public')
            ->open($path)->frame(\FFMpeg\Coordinate\TimeCode::fromSeconds(11))
            ->export()->toDisk('public')
->save('786_thumbnail.jpg');
```

what can be the problem here?

**Comment by pascalbaljet** [comment]
Check out the README, there's documentation about exporting a frame.
