### ISSUE TITLE
Encoding failed Error When converting Video to MP4

### ISSUE THREAD

**Issue by jpark00** [pascalbaljetmedia/laravel-ffmpeg#85]
I was getting a error when trying to convert a video into an MP4 (X264), running ffmpeg version 3.3.4-2.

Here is the exact error:
`FFMpeg\\Exception\\RuntimeException(code: 0): Encoding failed at /var/www/html/vendor/pbmedia/php-ffmpeg/src/FFMpeg/Media/Video.php:96, Alchemy\\BinaryDriver\\Exception\\ExecutionFailureException(code: 0): ffmpeg failed to execute command '/usr/bin/ffmpeg' '-y' '-i' '/tmp/laravel-ffmpegRkuTG7' '-threads' '12' '-vcodec' 'libx264' '-acodec' 'libfaac' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes5af1a185dc1c6tf93o/pass-5af1a185dc2bc' '/var/www/html/storage/app/temp/2018.05.07_20.01.15_5af0b08b82b59.3gp.mp4' at /var/www/html/vendor/pbmedia/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100`

Turns out that the "libfaac" audio encoder has been removed from ffmpeg (https://twitter.com/ffmpeg/status/782964711440588803). Was able to fix by passing 'aac' as the audio codec for the x264 instance:

`FFMpegFacade::fromDisk('local')->open('upload/user_' . $file->user_id . '/' . $file->filename)
                ->export()->toDisk('local')
                ->inFormat(new X264('aac'))->save('temp/'.$file->filename.'.mp4');`

Mostly adding this in case any other come across the same issue, though it might help to update the default x264 audio codec. Thanks.

**Comment by pascalbaljet** [comment]
This should be updated in the underlying library. They'll release a new major version in July and I'll probably rewrite this package when they release it.

**Comment by laravelcoder** [comment]
Any update or fix on how to get around this? i am having this issue as we speak?
