### ISSUE TITLE
Change Video framerate

### ISSUE THREAD

**Issue by codiiv** [pascalbaljetmedia/laravel-ffmpeg#89]
I am able to upload and convert to all sorts of formats. However, I also noticed that videos that are at a low framerate (15 fps for instance ) won't play. I would like to convert them to something a little higher like 25fps. Any ideas?

**Comment by pascalbaljet** [comment]
You can specify the output framerate by using the `'-f 25'` filter, see also: https://stackoverflow.com/questions/11004137/re-sampling-h264-video-to-reduce-frame-rate-while-maintaining-high-image-quality
