### ISSUE TITLE
Export issue unable to export using latest FFMpeg

### ISSUE THREAD

**Issue by swaraasolutions** [pascalbaljetmedia/laravel-ffmpeg#93]
Whenever i try to export on linux centos 7 with latest FFMpeg it shows the following error

> ratecontrol_init: can't open stats file

**Code that is called and stored in laravel.log**
`'/usr/bin/ffmpeg' '-y' '-i' '/home/vod/master/storage/app/public/videos/8cd57395-0d18-4a97-a734-e37c656a7042/8cd57395-0d18-4a97-a734-e37c656a7042.mp4' '-threads' '12' '-vcodec' 'libx264' '-acodec' 'libmp3lame' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes5b2bdbfc8f1e2ho4mf/pass-5b2bdbfc8f265' '/home/vod/master/storage/app/public/videos/8cd57395-0d18-4a97-a734-e37c656a7042/8cd57395-0d18-4a97-a734-e37c656a7042.mkv'`

If i remove -pass it works can you please help how i can disable pass or how to fix this issue.

Full debug attached.
[fulllog.txt](https://github.com/pascalbaljetmedia/laravel-ffmpeg/files/2124690/fulllog.txt)

Your help is much appreciated

**Comment by pascalbaljet** [comment]
Could you share your PHP code as well?

**Comment by swaraasolutions** [comment]
Here are the 2 snippets of PHP Code  one is just processing an MKV file and 2nd one is for exporting HLS from mp4

`FFMpeg::open( $this->videos->file_location )->export()->inFormat( new X264('libmp3lame') )->save( "videos/" . $this->videos->id . "/" . $this->videos->id . ".mkv" );`

`$lowBitrate = ( new X264 )->setKiloBitrate( 144 )->setVideoCodec( 'libx265' )->setAudioCodec( "libmp3lame" )->setAdditionalParameters( [
				"-strict",
				"-2",
			] );

			FFMpeg::open( $this->videos->file_location )
			      ->exportForHLS()
			      ->dontSortFormats()
			      ->setSegmentLength( 10 )// optional
			      ->addFormat( $lowBitrate )->save( "videos/" . $this->videos->id . "/" . $this->videos->id . '.m3u8' );`

**Comment by pascalbaljet** [comment]
And both generate the same error? Maybe the real error is this at the end of your log file:

`Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height`

**Comment by swaraasolutions** [comment]
Yes I agree but what seems to be causing this I have tried I different versions of ffmpeg from 2.5 till 4.0 any help on this will be much appreciated.ThanksVarun V.On 22 Jun 2018 12:46, pascalbaljet <notifications@github.com> wrote:And both generate the same error? Maybe the real error is this at the end of your log file:
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

**Comment by tpharaoh** [comment]
That was the perfect solution for my issue...
