### ISSUE TITLE
Driver [] is not supported.

### ISSUE THREAD

**Issue by Aryanr64x** [pascalbaljetmedia/laravel-ffmpeg#94]
I am using the following code 
`  FFMpeg::fromDisk('public/audio_profiles')
        ->open($this->filename)
        ->export()
        ->toDisk('public/audio_profiles')
        ->inFormat(new Aac)
        ->save('test.aac');`
And getting the following error
**Driver [] is not supported.**
All the video paths are correct . But The code doesn't seems to work

**Comment by pascalbaljet** [comment]
Please read the documentation about configuring [Laravel's Filesystem](https://laravel.com/docs/5.6/filesystem) and use the right disk.

**Comment by Aryanr64x** [comment]
I am using the right  disk
`  'default' => env('FILESYSTEM_DRIVER', 'local'),`
I am using the local disk and my directory structure follows public folder in its path . FileSystems are well set up . Seems to me a bug....

**Comment by pascalbaljet** [comment]
So your disk is called `public/audio_profiles`?

**Comment by Aryanr64x** [comment]
I have set the default disk to local so it points to the app folder

` 
'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],
`

**Comment by pascalbaljet** [comment]
Please read the documentation. You’re using the `fromDisk` wrong.

**Comment by pascalbaljet** [comment]
`Unable to probe` usally means the path is wrong or the file can’t be accessed.

**Comment by Aryanr64x** [comment]
Fixed the path and **Encoding failed**  error pops out .  Its a bit difficult to follow the error documentation  . The best thing about it is its integration with Laravel file system. I am opening a new
  issue on this error.

**Comment by pascalbaljet** [comment]
Try to search the existing issues for the _encoding failed_ issue:
https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues?utf8=✓&q=Encoding+failed

**Comment by Aryanr64x** [comment]
The encoding failed errors are conversion specific (depends upon  on what format you are converting into)
I am converting from mp3 to aac and I get the error . 
But when I am converting from mp3 to wav It gets converted successfully . 
[This will](https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/96) help in the development of the package.

**Comment by YTran-Prime** [comment]
# Help me
## Code
        $video = $this->findBy('id', $videoId);
        $newFile = FFMpeg::fromDisk('songs')
            ->open($video->path_audio)
            ->export()
            ->toDisk('local')
            ->inFormat(new \FFMpeg\Format\Audio\Aac)
            ->save(config_path('audio.aac'));

## error
The Response content must be a string or object implementing __toString(), "boolean" given.
