### ISSUE TITLE
Encoding Failed when converting from mp3 to aac?

### ISSUE THREAD

**Issue by Aryanr64x** [pascalbaljetmedia/laravel-ffmpeg#96]
I am converting from mp3 to aac using the following code
`
FFMpeg::fromDisK('local')
                ->open('public\audio-profiles\owl.mp3')
                ->export()
                ->toDisk('local')
                ->inFormat(new Aac)
                ->save('public\audio-profiles\output.aac');
`
I get the **encoding failed error**
Interestingly when I convert from mp3 to wav with similar code it works .

**Comment by pascalbaljet** [comment]
This issue has been discussed many times, both in this repo as well as in the underlying repo:
https://github.com/pascalbaljetmedia/laravel-ffmpeg/search?q=encoding+failed&type=Issues
https://github.com/PHP-FFMpeg/PHP-FFMpeg/search?q=encoding+failed&type=Issues
