### ISSUE TITLE
Unable to probe mp4 file

### ISSUE THREAD

**Issue by akhtar-husain** [pascalbaljetmedia/laravel-ffmpeg#99]
| Q              | A
| -------------- | ---
| Bug?           | yes
| New Feature?   | no
| Version Used   | ^2.1
| FFmpeg Version | 2.8.14
| OS             | Ubuntu 16.04

#### Actual Behavior
I am getting this error when I am trying to generate thumbnail from a mp4 video-
```
FFMpeg \ Exception \ RuntimeException
Unable to probe /var/www/html/project/storage/app/posts/buTMNB6k0yv5EOmLdl0um7BcCTWsN2NfHJe0sCi9.mp4
```
Below is my code 
```
\FFMpeg::open('posts/buTMNB6k0yv5EOmLdl0um7BcCTWsN2NfHJe0sCi9.mp4')
        ->getFrameFromSeconds(10)
        ->export()
        ->toDisk( 'thumbs')
        ->save('thumbnail.png');
```
Please help out on this issue.
Thanks

**Comment by bskiefer** [comment]
Having the same issue. Tried version 3.4 and the latest builds.

**Comment by pascalbaljet** [comment]
Please look through the issues and search for your problem, this has been asked a few times.
